services:

    _defaults: { public: true }

    user_connection:
        public: true
        alias: doctrine.dbal.ng2019_connection

    user_repository:
        public: true
        class: AppBundle\Action\Project\User\ProjectUserRepository
        arguments:
            - "@user_connection"

    user_provider:
        public: true
        class:  AppBundle\Action\Project\User\ProjectUserProvider
        arguments:
            - "%app_project_key%"
            - "@doctrine.dbal.ng2019_connection" # user connection
            - "@doctrine.dbal.ng2019_connection" # project person connection
            - "%users%"

    user_encoder:
        public: true
        class:  AppBundle\Action\Project\User\ProjectUserEncoder
        arguments:
            - "%cerad_user_master_password%"

    user_login_user:
        public: true
        class:  AppBundle\Action\Project\User\ProjectUserLoginUser
        arguments:
            - "main"
            - "@event_dispatcher"
            - "@security.token_storage"

    user_login_form:
        public: true
        class: AppBundle\Action\Project\User\Login\UserLoginForm
        arguments:
            - "@security.authentication_utils"
            - "@security.csrf.token_manager"
            - "@router"

# ==========================================================================
# User Create

    user_create_controller:
        public: true
        class:  AppBundle\Action\Project\User\Create\UserCreateController
        parent: abstract_controller
        arguments:
            - "@user_connection"
            - "@user_provider"
            - "@user_encoder"
            - "@user_create_form"

    user_create_view:
        public: true
        class:  AppBundle\Action\Project\User\Create\UserCreateView
        parent: abstract_view

    user_create_form:
        public: true
        class:  AppBundle\Action\Project\User\Create\UserCreateForm
        parent: abstract_form
        arguments:
            - "@user_connection"

# ==========================================================================
# Password management

    user_password_reset_request_command:
        public: true
        class: AppBundle\Action\Project\User\Password\ResetRequest\PasswordResetRequestCommand
        tags: [{ name: console.command }]
        arguments:
            - "@mailer"
            - "@user_repository"

    user_password_reset_request_form:
        public: true
        class:  AppBundle\Action\Project\User\Password\ResetRequest\PasswordResetRequestForm
        parent: abstract_form
        arguments:
            - "@user_repository"

    user_password_reset_request_controller:
        public: true
        class:  AppBundle\Action\Project\User\Password\ResetRequest\PasswordResetRequestController
        parent: abstract_controller
        arguments:
            - "@user_repository"
            - "@user_password_reset_request_form"

    user_password_reset_request_view:
        public: true
        class:  AppBundle\Action\Project\User\Password\ResetRequest\PasswordResetRequestView
        parent: abstract_view2
        arguments:
            - "@user_password_reset_request_form"

    user_password_reset_response_form:
        public: true
        class:  AppBundle\Action\Project\User\Password\ResetResponse\PasswordResetResponseForm
        parent: abstract_form
        arguments:
            - "@user_repository"

    user_password_reset_response_controller:
        public: true
        class:  AppBundle\Action\Project\User\Password\ResetResponse\PasswordResetResponseController
        parent: abstract_controller
        arguments:
            - "@user_encoder"
            - "@user_provider"
            - "@user_login_user"
            - "@user_repository"
            - "@user_password_reset_response_form"
            - "app_home"

    user_password_reset_response_view:
        public: true
        class:  AppBundle\Action\Project\User\Password\ResetResponse\PasswordResetResponseView
        parent: abstract_view2
        arguments:
            - "@user_password_reset_response_form"


# ==========================================================================
# Social network authentication

    user_authen_connect_controller:
        public: true
        class:  AppBundle\Action\Project\User\Authen\ConnectController
        parent: abstract_controller
        arguments:
            - "@user_authen_provider_factory"

    user_authen_callback_controller:
        public: true
        class:  AppBundle\Action\Project\User\Authen\CallbackController
        parent: abstract_controller
        arguments:
            - "@user_authen_provider_factory"
            - "@user_provider"

    user_authen_provider_factory:
        public: true
        class: AppBundle\Action\Project\User\Authen\ProviderFactory
        arguments:
            - "@router"
            - "%user_authen_providers%"

    user_authen_provider_google:
        public: true
        class: AppBundle\Action\Project\User\Authen\Provider\GoogleProvider
        arguments:
            - "@router"
            - "%provider_google_client_id%"
            - "%provider_google_client_secret%"

    user_authen_provider_facebook:
        public: true
        class: AppBundle\Action\Project\User\Authen\Provider\FacebookProvider
        arguments:
            - "@router"
            - "%provider_facebook_client_id%"
            - "%provider_facebook_client_secret%"
