services:

    user_connection:
        alias: doctrine.dbal.user_connection

    user_provider:
        class:  AppBundle\Action\Project\User\ProjectUserProvider
        arguments:
            - '@user_connection'
            - '%users%'

    user_encoder:
        class:  AppBundle\Action\Project\User\ProjectUserEncoder
        arguments:
            - '%cerad_user_master_password%'

    user_login_form:
        class: AppBundle\Action\Project\User\Login\UserLoginForm
        arguments:
            - '@security.authentication_utils'
            - '@security.csrf.token_manager'
            - '@router'

# ==========================================================================
# User Create

    user_create_controller:
        class: AppBundle\Action\Project\User\Create\UserCreateController
        parent: abstract_controller
        arguments:
            - '@user_connection'

    user_create_view:
        class: AppBundle\Action\Project\User\Create\UserCreateView
        parent: abstract_view

# ==========================================================================
# Password management

    user_password_reset_request_controller:
        class: AppBundle\Action\Project\User\PasswordResetRequest\PasswordResetRequestController
        parent: abstract_controller
        arguments:
            - '@user_connection'

    user_password_reset_request_view:
        class: AppBundle\Action\Project\User\PasswordResetRequest\PasswordResetRequestView
        parent: abstract_view
        arguments:
            - '@user_connection'


# ==========================================================================
# Socal network authentication

    user_authen_connect_controller:
        class: AppBundle\Action\Project\User\Authen\ConnectController
        parent: app_action_abstract_controller
        arguments:
            - '@user_authen_provider_factory'

    user_authen_callback_controller:
        class: AppBundle\Action\Project\User\Authen\CallbackController
        parent: app_action_abstract_controller
        arguments:
            - '@user_authen_provider_factory'
            - '@user_provider'

    user_authen_provider_factory:
        class: AppBundle\Action\Project\User\Authen\ProviderFactory
        arguments:
            - '@router'
            - '%user_authen_providers%'

    user_authen_provider_google:
        class: AppBundle\Action\Project\User\Authen\Provider\GoogleProvider
        arguments:
            - '@router'
            - '%provider_google_client_id%'
            - '%provider_google_client_secret%'

    user_authen_provider_facebook:
        class: AppBundle\Action\Project\User\Authen\Provider\FacebookProvider
        arguments:
            - '@router'
            - '%provider_facebook_client_id%'
            - '%provider_facebook_client_secret%'
