services:

    user_connection:
        alias: doctrine.dbal.ng2016_connection

    user_repository:
        class: AppBundle\Action\Project\User\ProjectUserRepository
        arguments:
            - '@user_connection'

    user_provider:
        class:  AppBundle\Action\Project\User\ProjectUserProvider
        arguments:
            - '%app_project_key%'
            - '@doctrine.dbal.ng2016_connection' # user connection
            - '@doctrine.dbal.ng2016_connection' # project person connection
            - '%users%'

    user_encoder:
        class:  AppBundle\Action\Project\User\ProjectUserEncoder
        arguments:
            - '%cerad_user_master_password%'

    user_login_user:
        class:  AppBundle\Action\Project\User\ProjectUserLoginUser
        arguments:
            - 'main'
            - '@event_dispatcher'
            - '@security.token_storage'

    user_login_form:
        class: AppBundle\Action\Project\User\Login\UserLoginForm
        arguments:
            - '@security.authentication_utils'
            - '@security.csrf.token_manager'
            - '@router'

# ==========================================================================
# User Create

    user_create_controller:
        class:  AppBundle\Action\Project\User\Create\UserCreateController
        parent: abstract_controller
        arguments:
            - '@user_connection'
            - '@user_provider'
            - '@user_encoder'
            - '@user_create_form'

    user_create_view:
        class:  AppBundle\Action\Project\User\Create\UserCreateView
        parent: abstract_view

    user_create_form:
        class:  AppBundle\Action\Project\User\Create\UserCreateForm
        parent: abstract_form
        arguments:
            - '@user_connection'

# ==========================================================================
# Password management

    user_password_reset_request_command:
        class: AppBundle\Action\Project\User\Password\ResetRequest\PasswordResetRequestCommand
        tags: [{ name: console.command }]
        arguments:
            - '@mailer'
          #- '@swiftmailer.transport.real' # Not available in production with no spool set
            - '@user_repository'

    user_password_reset_request_form:
        class:  AppBundle\Action\Project\User\Password\ResetRequest\PasswordResetRequestForm
        parent: abstract_form
        arguments:
            - '@security.authentication_utils'
            - '@user_repository'

    user_password_reset_request_controller:
        class:  AppBundle\Action\Project\User\Password\ResetRequest\PasswordResetRequestController
        parent: abstract_controller
        arguments:
            - '@mailer'
            - '@user_repository'
            - '@user_password_reset_request_form'

    user_password_reset_request_view:
        class:  AppBundle\Action\Project\User\Password\ResetRequest\PasswordResetRequestView
        parent: abstract_view
        arguments:
            - '@user_password_reset_request_form'

    user_password_reset_response_form:
        class:  AppBundle\Action\Project\User\Password\ResetResponse\PasswordResetResponseForm
        parent: abstract_form
        arguments:
            - '@user_repository'

    user_password_reset_response_controller:
        class:  AppBundle\Action\Project\User\Password\ResetResponse\PasswordResetResponseController
        parent: abstract_controller
        arguments:
            - '@user_encoder'
            - '@user_provider'
            - '@user_login_user'
            - '@user_repository'
            - '@user_password_reset_response_form'
            - 'app_home'

    user_password_reset_response_view:
        class:  AppBundle\Action\Project\User\Password\ResetResponse\PasswordResetResponseView
        parent: abstract_view
        arguments:
            - '@user_password_reset_response_form'


# ==========================================================================
# Socal network authentication

    user_authen_connect_controller:
        class: AppBundle\Action\Project\User\Authen\ConnectController
        parent: app_action_abstract_controller
        arguments:
            - '@user_authen_provider_factory'

    user_authen_callback_controller:
        class: AppBundle\Action\Project\User\Authen\CallbackController
        parent: app_action_abstract_controller
        arguments:
            - '@user_authen_provider_factory'
            - '@user_provider'

    user_authen_provider_factory:
        class: AppBundle\Action\Project\User\Authen\ProviderFactory
        arguments:
            - '@router'
            - '%user_authen_providers%'

    user_authen_provider_google:
        class: AppBundle\Action\Project\User\Authen\Provider\GoogleProvider
        arguments:
            - '@router'
            - '%provider_google_client_id%'
            - '%provider_google_client_secret%'

    user_authen_provider_facebook:
        class: AppBundle\Action\Project\User\Authen\Provider\FacebookProvider
        arguments:
            - '@router'
            - '%provider_facebook_client_id%'
            - '%provider_facebook_client_secret%'
