parameters:
  app_project_key: AYSONationalGames2014
  app_project:
    info:
        key: AYSONationalGames2014
        slugs:
            - natgames
            - natgames2014
            
        status:   Active
        verified: Yes
        show_header_image: null
                
        fedId:     AYSO
        fedRoleId: AYSOV

        abbv:    "NG2014x"
        title:   "AYSO National Games 2014"
        desc:    "AYSO National Games 2014 - Section One, Califorina - June 30 to July 6"

        standings: natgames
        
        submit:  "Emails your application to Art Hundiak and yourself."
        prefix:   NatGames
             
        support:
            name: "Art Hundiak"
            email: "ahundiak@gmail.com"
            subject: "NG2016 ZAYSO question..."
            phone: 256-457-5943
              
        schedules:
            name: "Rick Roberts"
            email: "web.ng2016@gmail.com"
            subject: "NG2016 schedule question..."
            phone: 310-920-8209
            
        assignor:
            name:  "Tom Tobin"
            email: "spsoccerref@earthlink.net"
            phone:  661-644-5096

        administrator:
            name:  "Tom Bobadilla"
            email: "thomasbobadilla@ayso.org"
            phone:  424-221-7980

        system:
            name:  "AYSO National Games 2014"
            email: "no.response.ng2014@gmail.com"
            phone:  ""

        programs:
            Core:  Core
            Extra: Extra

        dates:
            '2014-07-02': Wed # Soccerfest
            '2014-07-03': Thu # Pool Play
            '2014-07-04': Fri # Pool Play
            '2014-07-05': Sat # Pool Play and Quarter Finals
            '2014-07-06': Sun # Semi and Finals

        genders:
            B: Boys
            G: Girls

        ages:
            VIP: VIP
            U10: U10
            U12: U12
            U14: U14
            U16: U16
            U19: U19

        search_defaults:
            projects: ['AYSONationalGames2014']
            programs: ['Core']
            dates:    ['2014-07-03']
            genders:  ['B']
            ages:     ['U12']

        search_controls:
            dates:
                label: Days
            programs:
                label: Programs
            genders:
                label: Genders
            ages:
                label: Ages

        choices:
            dates:
                '2014-07-02': Wed # Soccerfest
                '2014-07-03': Thu # Pool Play
                '2014-07-04': Fri # Pool Play
                '2014-07-05': Sat # Pool Play and Quarter Finals
                '2014-07-06': Sun # Semi and Finals

            programs:
                Core:  Core
                Extra: Extra

            genders:
                B: Boys
                G: Girls

            ages:
                VIP: VIP
                U10: U10
                U12: U12
                U14: U14
                U16: U16
                U19: U19

            pools:
                Core:
                    B:
                        U10: [A,B,C,D,E,F,G,H,I,J,K,L]
                        U12: [A,B,C,D]
                        U14: [A,B,C,D]
                        U16: [A,B,C,D]
                        U19: [A,B,C,D]
                    G:
                        U10: [A,B,C,D,E,F,G,H,I,J,K,L]
                        U12: [A,B,C,D]
                        U14: [A,B,C,D]
                        U16: [A,B,C,D]
                        U19: [A,B,C,D]

    # ==============================================
    # For the schedule search form
    searches:
      
      dates:
        type:     checkbox
        label:    Days
        default: ['2014-07-03']
        choices:
          'All'       : All
          '2014-07-02': Wed
          '2014-07-03': Thu
          '2014-07-04': Fri
          '2014-07-05': Sat
          '2014-07-06': Sun
          
      genders:
        type:    checkbox
        label:   Genders
        default: ~
        choices:
          All: All
          B:   Boys
          G:   Girls
          
      ages:
        type:    checkbox
        label:   Ages
        default: [U10]
        choices:
          All: All
          VIP: VIP
          U10: U10
          U12: U12
          U14: U14
          U16: U16
          U19: U19
          #Adult: Adult
        
      programs:
        type:    checkbox
        label:   Programs
        default: [Core]
        choices:
          All: All
          Core:  Core
          Extra: Extra
    
    #times: # Want this to be a select
    #  start: 0600
    #  end:   2000
    
      venues:
        type:    checkbox
        label:   Venues
        default: ~
        choices:
          RAL-AB:   Ab Brown Soccer Complex, Riverside
          RAL-RP:   Reid Park, Riverside
          TOA-CP:   Columbia Park, Torrance
          TOA-FoD:  Field of Dreams, San Pedro
          TOA-LLP:  Ladera Linda Park, Rancho Palos Verdes
          TOA-MSF:  Maple Street Fields, Torrance
          TOA-PMS:  Parras Middle School, Redondo Beach
          TOA-RBHS: Redondo Beach High School, Redondo Beach
          TOA-WHS:  West High School, Torrance
          
      #select:
      #  type:   checkbox
      #  label:  Matches
      #  default: [Open,Declined,TurnBack]
      #  choices:
      #      All:        All
      #      Open:       Open
      #      Requested:  Req
      #      Reviewing:  Rev
      #      Pending:    Pend
      #      Published:  Pub
      #      Accepted:   Acc
      #      Declined:   Dec
      #      TurnBack:   TB
    
    # ==================================================
    # Basic volunteer plan
    basic:
      attending:
        type:    select
        label:   I will attend the games
        default: na
        choices:
          na:    Not yet answered
          no:    No
          yes:   Yes - For Sure
          yesx:  Yes - If my team is selected
          maybe: Maybe
                    
      refereeing:
        type:    select
        label:   I will referee
        default: no
        choices: { no: No, yes: Yes, maybe: Not Sure }
        
      venue:
        type:    select
        label:   I will work at
        default: na
        choices: 
          na:    Not yet answered
          core:  Torrance/Redondo Beach (CORE site)
          extra: Riverside (EXTRA site)
          other: Where needed (either site)
           
#     refLevelCR:
#       type:    select
#       label:   Level to center at
#       default: na
#       choices: { na: na, U10: U10, U12: U12, U14: U14, U16: U16, U19: U19
             
#     refLevelAR:
#       type:    select
#       label:   Level to assist at
#       default: na
#       choices: { na: na, U10: U10, U12: U12, U14: U14, U16: U16, U19: U19
             
      willInstruct:
        type:    select
        label:   I am certified Instructor
        default: no
        choices: { no: No, ri: Referee Instructor, ari: Advanced Referee Instructor, nri: National Referee Instructor}
           
      willAssess:
        type:    select
        label:   I am certified Assessor
        default: no
        choices: { no: No, ra: Referee Assessor, nra: National Referee Assessor}
           
      willMentor:
        type:    select
        label:   I will be available as a mentor
        default: no
        choices: { no: No, yes: Yes}
           
      wantMentor:
        type:    select
        label:   I would like to work with a mentor
        default: no
        choices: { no: No, yes: Yes}
           
      #willAssess:
      #  type:    select
      #  label:   I will do assessments/observations
      #  default: no
      #  choices: { no: No, yes: Yes, maybe: Not Sure}
      #     
      #wantAssess:
      #  type:    select
      #  label:   I request an assessment or observation
      #  default: no
      #  choices: 
      #    no:           No 
      #    Informal:     Informal 
      #    Intermediate: Intermediate
      #    AdvancedCR:   Advanced CR
      #    AdvancedAR:   Adcanced AR
      #    AdvancedCRAR: Advanced CR and AR
      #    NationalCR:   National CR
      #    NationalAR:   Advanced AR
      #    NationalCRAR: National CR and AR
             
      coaching:
        type:    select
        label:   I will coach or manage a team
        default: no
        choices: { no: No, yes: Yes, maybe: Not Sure}
           
      volunteering:
        type:    select
        label:   I will volunteer for other jobs
        default: no
        choices: { no: No, yes: Yes, maybe: Not Sure}
           
      playing:
        type:    select
        label:   I have (or am) a player in the games
        default: no
        choices: { no: No, yes: Yes, player: Yes - I am a player }
           
      opening:
        type:    select
        label:   I will attend the Tuesday Night Opening Ceremony?
        default: no
        choices: { no: No, yesRAL: Yes in Riverside, yesTOA: Yes in Torrance, maybe: Not Sure}
        
      tshirt:
        type:    select
        label:   T-Shirt Size
        default: na
        choices: 
          na:        na
          youthm:    Youth Medium 
          youthl:    Youth Large
          adults:    Adult Small
          adultm:    Adult Medium
          adultl:    Adult Large
          adultlx:   Adult Large X
          adultlxx:  Adult Large XX
          adultlxxx: Adult Large XXX
             
      shuttle:
        type:    select
        label:   I need shuttle service during the games
        default: no
        choices: { no: No, yes: Yes, maybe: Not Sure}
           
      housing:
        type:    select
        label:   I would use low cost referee housing
        default: no
        choices: { no: No, yes: Yes, maybe: Not Sure}
           
      #hotel:
      #  type:  text
      #  label: Hotel staying at
      #  size:  30
      
      availSatAfter:
        type:    select
        label:   Available Saturday Afternoon (Quarter Finals)
        default: no
        choices: { no: No, yes: Yes, maybe: Yes - If My Team Advances}
        
      availSunMorn:
        type:    select
        label:   Available Sunday Morning (Semi Finals)
        default: no
        choices: { no: No, yes: Yes, maybe: Yes - If My Team Advances}
        
      availSunAfter:
        type:    select
        label:   Available Sunday Afternoon (Finals)
        default: no
        choices: { no: No, yes: Yes, maybe: Yes - If My Team Advances}
        
      notes:
        type:  textarea
        label: Notes
        rows:  5
        cols:  40
        
    # Break out availability
    avail:
      
      AvailWen:
        type:    select
        label:   Available Wednesday (Jamborees)
        default: no
        choices: { no: No, yesAM: Yes in the Morning, yesPM: Yes in the afternoon, maybe: Not Sure}
           
      AvailThu:
        type:    select
        label:   Available Thursday (Pool Play)
        default: no
        choices: { no: No, yesAM: Yes in the Morning, yesPM: Yes in the afternoon, maybe: Not Sure}

      AvailFri:
        type:    select
        label:   Available Friday (Pool Play)
        default: no
        choices: { no: No, yesAM: Yes in the Morning, yesPM: Yes in the afternoon, maybe: Not Sure}

      AvailSatMorn:
        type:    select
        label:   Available Saturday Morning (Pool Play)
        default: no
        choices: { no: No, yesAM: Yes in the Morning, yesPM: Yes in the afternoon, maybe: Not Sure}
           
      AvailSatAfter:
        type:    select
        label:   Available Saturday Afternoon (Quarter Finals)
        default: no
        choices: { no: No, yesAM: Yes in the Morning, yesPM: Yes in the afternoon, maybe: Yes - If My Team Advances}

      AvailSunMorn:
        type:    select
        label:   Available Sunday Morning (Semi-Finals)
        default: no
        choices: { no: No, yesAM: Yes in the Morning, yesPM: Yes in the afternoon, maybe: Yes - If My Team Advances}

      AvailSunAfter:
        type:    select
        label:   Available Sunday Afternoon (Finals)
        default: no
        choices: { no: No, yesAM: Yes in the Morning, yesPM: Yes in the afternoon, maybe: Yes - If My Team Advances}
