parameters:

  app_project_key: AYSONationalGames2019

  app_project_fed_role_key: AYSOV

  app_project:
    info:
        key: AYSONationalGames2019 # For now until we migrate games

        slugs: [natgames, ng2016]

        status: Active
                
        fedId:     AYSO
        fedRoleId: AYSOV

        abbv:    "NG2019"
        title:   "AYSO National Games 2019"
        desc:    "AYSO National Games 2019 - Waipio Peninsula Soccer Complex, Waipahu, HI - June 30 to July 7, 2019"
        prefix:  'NatGames2019'

        regYear: 'MY2018'

        pageTemplate: 'Zayso\Project\NG2019\NG2019PageTemplate'

        support:
            name: "Art Hundiak"
            email: "ahundiak@gmail.com"
            subject: "NG2019 zAYSO question..."
            phone: 256-457-5943
              
        schedules:
            name: "Rob McCarthy"
            email: "soccer.ref62@yahoo.com"
            subject: "NG2019 schedule question..."
            phone: 808-286-9280
            
        assignor:
            name: "Rob McCarthy"
            email: "soccer.ref62@yahoo.com"
            subject: "Referee Assignments"
            phone: 808-286-9280

        administrator:
            name: "Rob McCarthy"
            email: "soccer.ref62@yahoo.com"
            subject: "Question for NG Referee Administrator"
            phone: 808-286-9280

        system:
            name:  "Zayso Admin"
            email: "noreply@zayso.org"
            phone:  ""

        dates:
            '2019-07-02': Wed # Soccerfest 2019
            '2019-07-03': Thu # Pool Play
            '2019-07-04': Thu # Pool Play
            '2019-07-05': Fri # Pool Play
            '2019-07-06': Sat # Quarter Finals
            '2019-07-07': Sun # Semi and Finals

        programs:
            Core: Core

        genders:
            B:  Boys
            G:  Girls

        ages:
            VIP: VIP
            10U: 10U
            12U: 12U
            14U: 14U
            16U: 16U
            18U: 18U

        search_defaults:
            projects: ['AYSONationalGames2019']
            dates:    ['2019-07-02']
            genders:  ['B']
            ages:     ['12U']

        search_controls:
            dates:
                label: Days
            genders:
                label: Genders
            ages:
                label: Ages

        choices:
            dates:
            '2019-07-02': Tue # Soccerfest 2019
            '2019-07-03': Wed # Pool Play
            '2019-07-04': Thu # Pool Play
            '2019-07-05': Fri # Pool Play
            '2019-07-06': Sat # Quarter Finals
            '2019-07-07': Sun # Semi and Finals

            programs:
                Core:  Core

            genders:
                B: Boys
                G: Girls

            ages:
                VIP: VIP
                10U: 10U
                12U: 12U
                14U: 14U
                16U: 16U
                18U: 18U

            pools:
                Core:
                    B:
                        10U: [A,B,C,D,E,F,G,H,I,J,K,L]
                        12U: [A,B,C,D]
                        14U: [A,B,C,D]
                        16U: [A,B,C,D]
                        18U: [A,B,C,D]
                    G:
                        10U: [A,B,C,D,E,F,G,H,I,J,K,L]
                        12U: [A,B,C,D]
                        14U: [A,B,C,D]
                        16U: [A,B,C,D]
                        18U: [A,B,C,D]

        levels:
            AYSO_B10U_Core:
                program: Core
                gender:  B
                age:     10U
                div:     B10U

            AYSO_G10U_Core:
                program: Core
                gender:  G
                age:     10U
                div:     G10U

            AYSO_B12U_Core:
                program: Core
                gender:  B
                age:     12U
                div:     B12U

            AYSO_G12U_Core:
                program: Core
                gender:  G
                age:     12U
                div:     G12U

        pools:

        venues:
            Fields: Waipio

        fields:

  # ==================================================
  # Basic volunteer plan for the form
  app_project_registration_form_controls:

      name:
          type:        text
          label:       Registration Name
          placeHolder: Your Name
          required:    true
          transformex: unique_project_name_transformer

      email:
          type:        email
          label:       Registration Email
          placeHolder: Your Email
          required:    true

      phone:
          type:        phone
          label:       Mobile Phone
          placeHolder: Your Phone Number
          required:    false
          transformer: phone_transformer

      fedKey: {}
      orgKey: {}
      refereeBadge: {}

    # willAttend:    { group: plans }
      willReferee:   { group: plans }
      willVolunteer: { group: plans }
      willCoach:     { group: plans }
      shirtSize: {}

      availTue:     { group: avail }
      availWed:      { group: avail }
      availThu:      { group: avail }
      availFri:      { group: avail }
      availSatMorn:  { group: avail }
      availSatAfter: { group: avail }
      availSunMorn:  { group: avail }
      availSunAfter: { group: avail }

      notesUser: {}

  app_project_controls:

        willAttend:
            type:    select
            label:   Will Attend
            default: na
            choices:
                na:    Not yet answered
                no:    No
                yes:   Yes - For Sure
                yesx:  Yes - If my team is selected
                maybe: Maybe

        willVolunteer:
            type:    select
            label:   Will Volunteer
            default: no
            choices: { no: No, yes: Yes (besides refereeing), maybe: Maybe }

        willCoach:
            type:    select
            label:   Will Coach
            default: no
            choices: { no: No, yes: Yes (or assist), maybe: Maybe }

        willReferee:
            type:    select
            label:   Will Referee
            default: no
            choices: { no: No, yes: Yes, maybe: Maybe }

        refereeBadge:
            type:    select
            label:   AYSO Referee Badge
            default: na
            choices:
                None:         NA
                Regional:     Regional
                Intermediate: Intermediate
                Advanced:     Advanced
                National:     National
                National_1:   National 1
                National_2:   National 2
                Assistant:    Assistant
                U8Official:   U8 Official

        shirtSize:
            type:    select
            label:   T-Shirt Size
            default: na
            choices:
                na:         na
                youths:     Youth Small
                youthm:     Youth Medium
                youthl:     Youth Large
                adults:     Adult Small
                adultm:     Adult Medium
                adultl:     Adult Large
                adultlx:    Adult Large X
                adultlxx:   Adult Large XX
                adultlxxx:  Adult Large XXX
                adultlxxxx: Adult Large XXXX

        notesUser:
          type:  textarea
          label: Notes
          rows:  5
          cols:  40

        notes:
          type:  textarea
          label: Notes
          rows:  5
          cols:  60

        fedKey:
            type:        text # aysoid
            label:       AYSO Volunteer ID
            href:        eayso.org
            placeHolder: 8-8 digit number
            transformer: Zayso\Fed\Ayso\AysoIdTransformer
            #constraints: ['aysoid_constraint'] # Maybe class name?

        orgKey:
            type:        text # sar
            label:       AYSO Section/Area/Region
            href:        eayso.org
            placeHolder: 5/C/0894
            transformer: Zayso\Fed\Ayso\AysoIdTransformer
            #constraints: ['aysoid_constraint'] # Maybe class name?

        availSatMorn:
            type:    select
            label:   Available Saturday Morning (Pool Play)
            default: no
            choices: { no: No, yes: Yes, maybe: Maybe }

        availSatAfter:
            type:    select
            label:   Available Saturday Afternoon (Qtr-Finals)
            default: no
            choices: { no: No, yes: Yes, maybe: Maybe }

        availSunMorn:
            type:    select
            label:   Available Sunday Morning (Semi-Finals)
            default: no
            choices: { no: No, yes: Yes, maybe: Maybe }

        availSunAfter:
            type:    select
            label:   Available Sunday Afternoon (Finals)
            default: no
            choices: { no: No, yes: Yes, maybe: Maybe}

        availTue:
            type:    select
            label:   Available Tuesday (Soccerfest)
            default: no
            choices: { no: No, yes: Yes, maybe: Maybe}

        availWed:
            type:    select
            label:   Available Wednesday (Pool Play)
            default: no
            choices: { no: No, yes: Yes, maybe: Maybe}

        availThu:
            type:    select
            label:   Available Thursday (Pool Play)
            default: no
            choices: { no: No, yes: Yes, maybe: Maybe}

        availFri:
            type:    select
            label:   Available Friday (Pool Play)
            default: no
            choices: { no: No, yes: Yes, maybe: Maybe}
