parameters:

  app_project_key: AYSONationalGames2016

  app_project_fed_role_key: AYSOV

  app_project:
    info:
        key: AYSONationalGames2014 # For now until we migrate
        slugs:
            - natgames
            - ng2016
            
        status:   Active
        verified: Yes
        show_header_image: null
                
        fedId:     AYSO
        fedRoleId: AYSOV

        abbv:    "NG2016"
        title:   "AYSO National Games 2016"
        desc:    "AYSO National Games 2016 - Palm Beach County, Florida - July 5th to July 10th"
        results: natgames
        
        submit:  "Emails your application to Art Hundiak and yourself."
        prefix:   NatGames2016
             
        support:
            name: "Art Hundiak"
            email: "ahundiak@gmail.com"
            subject: "NG2016 ZAYSO question..."
            phone: 256-457-5943
              
        schedules:
            name: "Rick Roberts"
            email: "web.ng2016@gmail.com"
            subject: "NG2016 schedule question..."
            phone: 310-920-8209
            
        assignor:
            name:  "Tom Tobin"
            email: "spsoccerref@earthlink.net"
            phone:  661-644-5096

        administrator:
            name:  "Tom Bobadilla"
            email: "thomasbobadilla@ayso.org"
            phone:  424-221-7980

        system:
            name:  "AYSO National Games 2016"
            email: "no.response.ng2016@gmail.com"
            phone:  ""

        dates:
            #- '2016-07-06' # Wed Soccerfest
            #- '2016-07-07' # Thu Pool Play
            #- '2016-07-08' # Fri Pool Play
            #- '2016-07-09' # Sat Pool Play and Quarter Finals
            #- '2016-07-10' # Sun Semi and Finals
            '2014-07-02': Wed # Soccerfest 2014
            '2014-07-03': Thu # Pool Play
            '2014-07-04': Fri # Pool Play
            '2014-07-05': Sat # Pool Play and Quarter Finals
            '2014-07-06': Sun # Semi and Finals

        programs:
            Core: Core

        genders:
            B:  Boys
            G:  Girls

        ages:
            VIP: VIP
            U10: U10
            U12: U12
            U14: U14
            U16: U16
            U19: U19

        search_defaults:
            projects: ['AYSONationalGames2014']
            programs: ['Core']
            dates:    ['2014-07-03']
            genders:  ['B']
            ages:     ['U12']

        search_controls:
            dates:
                label: Days
            programs:
                label: Programs
            genders:
                label: Genders
            ages:
                label: Ages

        choices:
            dates:
                '2014-07-02': Wed # Soccerfest
                '2014-07-03': Thu # Pool Play
                '2014-07-04': Fri # Pool Play
                '2014-07-05': Sat # Pool Play and Quarter Finals
                '2014-07-06': Sun # Semi and Finals

            programs:
                Core:  Core
                Extra: Extra

            genders:
                B: Boys
                G: Girls

            ages:
                VIP: VIP
                U10: U10
                U12: U12
                U14: U14
                U16: U16
                U19: U19

            pools:
                Core:
                    B:
                        U10: [A,B,C,D,E,F,G,H,I,J,K,L]
                        U12: [A,B,C,D]
                        U14: [A,B,C,D]
                        U16: [A,B,C,D]
                        U19: [A,B,C,D]
                    G:
                        U10: [A,B,C,D,E,F,G,H,I,J,K,L]
                        U12: [A,B,C,D]
                        U14: [A,B,C,D]
                        U16: [A,B,C,D]
                        U19: [A,B,C,D]

        levels:
            AYSO_U10B_Core:
                program: Core
                gender:  B
                age:     U10
                div:     U10B

            AYSO_U10G_Core:
                program: Core
                gender:  G
                age:     U10
                div:     U10G

            AYSO_U12B_Core:
                program: Core
                gender:  B
                age:     U12
                div:     U12B

            AYSO_U12G_Core:
                program: Core
                gender:  G
                age:     U12
                div:     U12G

        pools:

        venues:
            Polo: Polo Grounds

        fields:


    # ==================================================
    # Basic volunteer plan
    # This section is depreciated
    # app_project_plans for 2016
    plans:
      venue:
        type:    select
        label:   I will work at
        default: na
        choices: 
          na:    Not yet answered
          core:  Torrance/Redondo Beach (CORE site)
          extra: Riverside (EXTRA site)
          other: Where needed (either site)
           
#     refLevelCR:
#       type:    select
#       label:   Level to center at
#       default: na
#       choices: { na: na, U10: U10, U12: U12, U14: U14, U16: U16, U19: U19
             
#     refLevelAR:
#       type:    select
#       label:   Level to assist at
#       default: na
#       choices: { na: na, U10: U10, U12: U12, U14: U14, U16: U16, U19: U19
             
      willInstruct:
        type:    select
        label:   I am certified Instructor
        default: no
        choices: { no: No, ri: Referee Instructor, ari: Advanced Referee Instructor, nri: National Referee Instructor}
           
      willAssess:
        type:    select
        label:   I am certified Assessor
        default: no
        choices: { no: No, ra: Referee Assessor, nra: National Referee Assessor}
           
      willMentor:
        type:    select
        label:   I will be available as a mentor
        default: no
        choices: { no: No, yes: Yes}
           
      wantMentor:
        type:    select
        label:   I would like to work with a mentor
        default: no
        choices: { no: No, yes: Yes}

      coaching:
        type:    select
        label:   I will coach or manage a team
        default: no
        choices: { no: No, yes: Yes, maybe: Not Sure}

           
      playing:
        type:    select
        label:   I have (or am) a player in the games
        default: no
        choices: { no: No, yes: Yes, player: Yes - I am a player }
           
      opening:
        type:    select
        label:   I will attend the Tuesday Night Opening Ceremony?
        default: no
        choices: { no: No, yesRAL: Yes in Riverside, yesTOA: Yes in Torrance, maybe: Not Sure}
        
      tshirt:
        type:    select
        label:   T-Shirt Size
        default: na
        choices: 
          na:        na
          youthm:    Youth Medium 
          youthl:    Youth Large
          adults:    Adult Small
          adultm:    Adult Medium
          adultl:    Adult Large
          adultlx:   Adult Large X
          adultlxx:  Adult Large XX
          adultlxxx: Adult Large XXX
             
      shuttle:
        type:    select
        label:   I need shuttle service during the games
        default: no
        choices: { no: No, yes: Yes, maybe: Not Sure}
           
      housing:
        type:    select
        label:   I would use low cost referee housing
        default: no
        choices: { no: No, yes: Yes, maybe: Not Sure}
           
      #hotel:
      #  type:  text
      #  label: Hotel staying at
      #  size:  30
      
      availSatAfter:
        type:    select
        label:   Available Saturday Afternoon (Quarter Finals)
        default: no
        choices: { no: No, yes: Yes, maybe: Yes - If My Team Advances}
        
      availSunMorn:
        type:    select
        label:   Available Sunday Morning (Semi Finals)
        default: no
        choices: { no: No, yes: Yes, maybe: Yes - If My Team Advances}
        
      availSunAfter:
        type:    select
        label:   Available Sunday Afternoon (Finals)
        default: no
        choices: { no: No, yes: Yes, maybe: Yes - If My Team Advances}
        
      notes:
        type:  textarea
        label: Notes
        rows:  5
        cols:  40
        
    # Break out availability
    avail:
      
      AvailWen:
        type:    select
        label:   Available Wednesday (Jamborees)
        default: no
        choices: { no: No, yesAM: Yes in the Morning, yesPM: Yes in the afternoon, maybe: Not Sure}
           
      AvailThu:
        type:    select
        label:   Available Thursday (Pool Play)
        default: no
        choices: { no: No, yesAM: Yes in the Morning, yesPM: Yes in the afternoon, maybe: Not Sure}

      AvailFri:
        type:    select
        label:   Available Friday (Pool Play)
        default: no
        choices: { no: No, yesAM: Yes in the Morning, yesPM: Yes in the afternoon, maybe: Not Sure}

      AvailSatMorn:
        type:    select
        label:   Available Saturday Morning (Pool Play)
        default: no
        choices: { no: No, yesAM: Yes in the Morning, yesPM: Yes in the afternoon, maybe: Not Sure}
           
      AvailSatAfter:
        type:    select
        label:   Available Saturday Afternoon (Quarter Finals)
        default: no
        choices: { no: No, yesAM: Yes in the Morning, yesPM: Yes in the afternoon, maybe: Yes - If My Team Advances}

      AvailSunMorn:
        type:    select
        label:   Available Sunday Morning (Semi-Finals)
        default: no
        choices: { no: No, yesAM: Yes in the Morning, yesPM: Yes in the afternoon, maybe: Yes - If My Team Advances}

      AvailSunAfter:
        type:    select
        label:   Available Sunday Afternoon (Finals)
        default: no
        choices: { no: No, yesAM: Yes in the Morning, yesPM: Yes in the afternoon, maybe: Yes - If My Team Advances}


    # ==================================================
    # Basic volunteer plan for the form
  app_project_registration_form_controls:

      name:
          type:        text
          label:       Registration Name
          placeHolder: Your Name
          required:    true

      email:
          type:        email
          label:       Registration Email
          placeHolder: Your Name
          required:    true

      phone:
          type:        phone
          label:       Registration Phone #
          placeHolder: Your Phone Number
          required:    false

      fedKey:
          type:        integer # aysois
          label:       AYSO Volunteer ID
          href:        eayso.org
          placeHolder: 8-digit number

      willAttend:    { group: plans }
      willVolunteer: { group: plans }
      willReferee:   { group: plans }

  app_project_controls:

        willAttend:
            type:    select
            label:   Will Attend
            default: na
            choices:
                na:    Not yet answered
                no:    No
                yes:   Yes - For Sure
                yesx:  Yes - If my team is selected
                maybe: Maybe

        willVolunteer:
            type:    select
            label:   Will Volunteer
            default: no
            choices: { no: No, yes: Yes, maybe: Not Sure }

        willReferee:
            type:    select
            label:   Will Referee
            default: no
            choices: { no: No, yes: Yes, maybe: Not Sure }

        refereeBadge:
            type:    select
            label:   AYSO Referee Badge
            default: na
            choices:
                None:         None
                Regional:     Regional
                Intermediate: Intermediate
                Advanced:     Advanced
                National:     National
                National_1:   National 1
                National_2:   National 2
                Assistant:    Assistant
                U8Official:   U8 Official

