schedule_team_2016:
    path: /team.{_format}
    defaults:
        _format: html
        _controller: schedule_team_controller_2016
        _view_html:  schedule_team_view_html_2016
        _view_xls:   schedule_team_view_xls_2016
        _view_csv:   schedule_team_view_csv_2016
        _view_txt:   schedule_team_view_txt_2016

schedule_official_2016:
    path: /official.{_format}
    defaults:
        _format: html
        _controller: schedule_official_controller_2016
        _view_html:  schedule_official_view_html_2016
        _view_xls:   schedule_official_view_xls_2016
        _view_csv:   schedule_official_view_csv_2016
        _view_txt:   schedule_official_view_txt_2016

schedule_assignor_2016:
    path: /assignor.{_format}
    defaults:
        _format: html
        _controller: schedule_assignor_controller_2016
        _view_html:  schedule_assignor_view_html_2016
        _view_xls:   schedule_assignor_view_xls_2016
        _view_csv:   schedule_assignor_view_csv_2016
        _view_txt:   schedule_assignor_view_txt_2016

schedule_game_2016:
    path: /game.{_format}
    defaults:
        _format: html
        _controller: schedule_game_controller_2016
        _view_html:  schedule_game_view_html_2016
        _view_xls:   schedule_game_view_xls_2016
        _view_csv:   schedule_game_view_csv_2016
        _view_txt:   schedule_game_view_txt_2016
        _view_pdf:   schedule_game_view_pdf
        _view_json:  schedule_game_view_json


schedule_medalroundcalc_2016:
    path: /medalroundcalc.{_format}
    defaults:
        _format: xls_qf
        _controller:    schedule_medalroundcalc_controller_2016
        _view_xls_qf:   schedule_medalroundcalc_view_xls_qf_2016
        _view_xls_sf:   schedule_medalroundcalc_view_xls_sf_2016
        _view_xls_fm:   schedule_medalroundcalc_view_xls_fm_2016

field_map:
    path: /field_map
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /pdf/master_field_layout.pdf