services:

    abstract_exporter_xls:
        class: AppBundle\Action\AbstractExporter
        arguments:
            - 'xls'

    abstract_exporter_csv:
        class: AppBundle\Action\AbstractExporter
        arguments:
            - 'csv'

    abstract_exporter_txt:
        class: AppBundle\Action\AbstractExporter
        arguments:
            - 'txt'

    schedule_finder_2016:
        class: AppBundle\Action\Schedule2016\ScheduleFinder
        arguments:
            - '@doctrine.dbal.ng2016games_connection' # gameConn
            - '@doctrine.dbal.ng2016games_connection' # regTeamConn

    schedule_template_2016:
        abstract: true
        calls:
            - ['setContainer',       ['@service_container']]
            - ['setRegPersonFinder', ['@reg_person_finder']]

    schedule_search_form_2016:
        class:  AppBundle\Action\Schedule2016\ScheduleSearchForm
        parent: abstract_form
        arguments:
            - '%project_choices%'
            - '%projects%'

    # ===============================================================
    # Schedule Game
    schedule_game_search_form_2016:
        class:  AppBundle\Action\Schedule2016\Game\ScheduleGameSearchForm
        parent: abstract_form
        arguments:
            - '%project_choices%'
            - '%projects%'

    schedule_game_controller_2016:
        class:  AppBundle\Action\Schedule2016\Game\ScheduleGameController
        parent: abstract_controller
        arguments:
            - '@schedule_game_search_form_2016'
            - '@schedule_finder_2016'
            - '%project_choices%'
            - '%projects%'

    schedule_game_template_2016:
        class:  AppBundle\Action\Schedule2016\ScheduleTemplate
        parent: schedule_template_2016
        arguments: ['Game Schedule']

    schedule_game_view_html_2016:
        class:  AppBundle\Action\Schedule2016\Game\ScheduleGameView
        parent: abstract_view2
        arguments:
            - '@schedule_game_search_form_2016'
            - '@schedule_game_template_2016'

    schedule_game_writer_excel:
        class:  AppBundle\Action\Schedule2016\Game\ScheduleGameWriterExcel

    schedule_game_view_xls_2016:
        class:  AppBundle\Action\Schedule2016\Game\ScheduleGameViewFile
        parent: abstract_view2
        arguments:
            - '@abstract_exporter_xls'
            
    schedule_game_view_csv_2016:
        class:  AppBundle\Action\Schedule2016\Game\ScheduleGameViewFile
        parent: abstract_view2
        arguments:
            - '@abstract_exporter_csv'
            
    schedule_game_view_txt_2016:
        class:  AppBundle\Action\Schedule2016\Game\ScheduleGameViewFile
        parent: abstract_view2
        arguments:
            - '@abstract_exporter_txt'

    # ===============================================================
    # Schedule Official

    schedule_official_controller_2016:
        class:  AppBundle\Action\Schedule2016\Official\ScheduleOfficialController
        parent: abstract_controller
        arguments:
            - '@schedule_search_form_2016'
            - '@schedule_finder_2016'
            - '%project_choices%'
            - '%projects%'

    schedule_official_template_2016:
        class:  AppBundle\Action\Schedule2016\ScheduleTemplate
        parent: schedule_template_2016
        arguments: ['Referee Game Schedule', true, false, '@game_official_assign_workflow']

    schedule_official_view_html_2016:
        class:  AppBundle\Action\Schedule2016\ScheduleView
        parent: abstract_view2
        arguments:
            - '@schedule_search_form_2016'
            - '@schedule_official_template_2016'

    schedule_official_view_xls_2016:
        class:  AppBundle\Action\Schedule2016\Official\ScheduleOfficialViewFile
        parent: abstract_view2
        arguments:
            - '@abstract_exporter_xls'

    schedule_official_view_txt_2016:
        class:  AppBundle\Action\Schedule2016\Official\ScheduleOfficialViewFile
        parent: abstract_view2
        arguments:
            - '@abstract_exporter_txt'

    # ===============================================================
    # Schedule Assignor

    schedule_assignor_controller_2016:
        class:  AppBundle\Action\Schedule2016\Assignor\ScheduleAssignorController
        parent: abstract_controller
        arguments:
            - '@schedule_search_form_2016'
            - '@schedule_finder_2016'
            - '%project_choices%'
            - '%projects%'

    schedule_assignor_template_2016:
        class:  AppBundle\Action\Schedule2016\ScheduleTemplate
        parent: schedule_template_2016
        arguments:
            - 'Assignor Game Schedule'
            -  true
            -  true
            - '@game_official_assign_workflow'
            - '@game_official_details_finder'

    schedule_assignor_view_html_2016:
        class:  AppBundle\Action\Schedule2016\ScheduleView
        parent: abstract_view2
        arguments:
            - '@schedule_search_form_2016'
            - '@schedule_assignor_template_2016'

    schedule_assignor_view_xls_2016:
        class:  AppBundle\Action\Schedule2016\Assignor\ScheduleAssignorViewFile
        parent: abstract_view2
        arguments:
            - '@abstract_exporter_xls'

    schedule_assignor_view_txt_2016:
        class:  AppBundle\Action\Schedule2016\Assignor\ScheduleAssignorViewFile
        parent: abstract_view2
        arguments:
            - '@abstract_exporter_txt'

    # ===============================================================
    # Schedule Team
    schedule_team_search_form_2016:
        class:  AppBundle\Action\Schedule2016\Team\ScheduleTeamSearchForm
        parent: abstract_form
        arguments:
            - '%project_choices%'
            - '%projects%'
            - '@schedule_finder_2016'

    schedule_team_controller_2016:
        class:  AppBundle\Action\Schedule2016\Team\ScheduleTeamController
        parent: abstract_controller
        arguments:
            - '@schedule_team_search_form_2016'
            - '@schedule_finder_2016'
            - '%project_choices%'
            - '%projects%'

    schedule_team_template_2016:
        class:  AppBundle\Action\Schedule2016\ScheduleTemplate
        parent: schedule_template_2016
        arguments: ['Team Schedule']

    schedule_team_view_html_2016:
        class:  AppBundle\Action\Schedule2016\Team\ScheduleTeamView
        parent: abstract_view2
        arguments:
            - '@schedule_team_search_form_2016'
            - '@schedule_team_template_2016'

    schedule_team_view_xls_2016:
        class:  AppBundle\Action\Schedule2016\Team\ScheduleTeamViewFile
        parent: abstract_view2
        arguments:
            - '@abstract_exporter_xls'
            
    schedule_team_view_csv_2016:
        class:  AppBundle\Action\Schedule2016\Team\ScheduleTeamViewFile
        parent: abstract_view2
        arguments:
            - '@abstract_exporter_csv'

    schedule_team_view_txt_2016:
        class:  AppBundle\Action\Schedule2016\Team\ScheduleTeamViewFile
        parent: abstract_view2
        arguments:
            - '@abstract_exporter_txt'
            
    # ===============================================================
    # Schedule MedalRoundLogic
    
    schedule_medalroundcalc_controller_2016:
        class: AppBundle\Action\Schedule2016\ScheduleMedalRoundController
        parent: abstract_controller
        arguments:
            - '@results_finder_2016'
            - '%project_choices%'

    schedule_medalround_calculator_2016:
        class: AppBundle\Action\Schedule2016\ScheduleMedalRoundCalculator
        
    schedule_medalroundcalc_view_xls_qf_2016:
        class: AppBundle\Action\Schedule2016\ScheduleMedalRoundViewFile
        parent: abstract_view2
        arguments:
            - 'qf'
            - '@schedule_medalround_calculator_2016'
            - '@results_finder_2016'
            - '@abstract_exporter_xls'

    schedule_medalroundcalc_view_xls_sf_2016:
        class: AppBundle\Action\Schedule2016\ScheduleMedalRoundViewFile
        parent: abstract_view2
        arguments:
            - 'sf'
            - '@schedule_medalround_calculator_2016'
            - '@results_finder_2016'
            - '@abstract_exporter_xls'

    schedule_medalroundcalc_view_xls_fm_2016:
        class: AppBundle\Action\Schedule2016\ScheduleMedalRoundViewFile
        parent: abstract_view2
        arguments:
            - 'fm'
            - '@schedule_medalround_calculator_2016'
            - '@results_finder_2016'
            - '@abstract_exporter_xls'


