services:

    schedule_finder_2016:
        class: AppBundle\Action\Schedule2016\ScheduleFinder
        arguments:
            - '@doctrine.dbal.ng2016games_connection' # gameConn
            - '@doctrine.dbal.ng2016games_connection' # poolTeamConn
            - '@doctrine.dbal.ng2016games_connection' # projectTeamConn

    schedule_template_2016:
        class: AppBundle\Action\Schedule2016\ScheduleTemplate
        calls: [['setContainer', ['@service_container']]]

    # ===============================================================
    # Schedule Game
    schedule_game_search_form_2016:
        class:  AppBundle\Action\Schedule2016\Game\ScheduleGameSearchForm
        parent: abstract_form
        arguments:
            - '%project_choices%'
            - '%projects%'

    schedule_game_controller_2016:
        class:  AppBundle\Action\Schedule2016\Game\ScheduleGameController
        parent: abstract_controller
        arguments:
            - '@schedule_game_search_form_2016'
            - '@schedule_finder_2016'
            - '%project_choices%'
            - '%projects%'

    schedule_game_view_html_2016:
        class:  AppBundle\Action\Schedule2016\Game\ScheduleGameView
        parent: abstract_view2
        arguments:
            - '@schedule_game_search_form_2016'
            - '@schedule_template_2016'

    # ===============================================================
    # Schedule Official

    schedule_official_search_form_2016:
        class:  AppBundle\Action\Schedule2016\Official\ScheduleOfficialSearchForm
        parent: abstract_form
        arguments:
            - '%project_choices%'
            - '%projects%'

    schedule_official_controller_2016:
        class:  AppBundle\Action\Schedule2016\Official\ScheduleOfficialController
        parent: abstract_controller
        arguments:
            - '@schedule_official_search_form_2016'
            - '@schedule_finder_2016'
            - '%project_choices%'
            - '%projects%'

    schedule_official_view_html_2016:
        class:  AppBundle\Action\Schedule2016\Official\ScheduleOfficialView
        parent: abstract_view2
        arguments:
            - '@schedule_official_search_form_2016'
            - '@schedule_template_2016'

    # ===============================================================
    # Schedule Team
    schedule_team_search_form_2016:
        class:  AppBundle\Action\Schedule2016\Team\ScheduleTeamSearchForm
        parent: abstract_form
        arguments:
            - '%project_choices%'
            - '%projects%'
            - '@schedule_finder_2016'

    schedule_team_controller_2016:
        class:  AppBundle\Action\Schedule2016\Team\ScheduleTeamController
        parent: abstract_controller
        arguments:
            - '@schedule_team_search_form_2016'
            - '@schedule_finder_2016'
            - '%project_choices%'
            - '%projects%'

    schedule_team_view_html_2016:
        class:  AppBundle\Action\Schedule2016\Team\ScheduleTeamView
        parent: abstract_view2
        arguments:
            - '@schedule_team_search_form_2016'
            - '@schedule_template_2016'
