services:

    schedule_finder_2016:
        class: AppBundle\Action\Schedule2016\ScheduleFinder
        arguments:
            - '@doctrine.dbal.ng2016games_connection' # gameConn
            - '@doctrine.dbal.ng2016games_connection' # poolTeamConn
            - '@doctrine.dbal.ng2016games_connection' # projectTeamConn

    # ===============================================================
    # Schedule Game
    schedule_game_controller_2016:
        class:  AppBundle\Action\Schedule2016\Game\ScheduleGameController
        parent: abstract_controller
        arguments:
            - '@schedule_finder_2016'

    schedule_game_view_html_2016:
        class:  AppBundle\Action\Schedule2016\Game\ScheduleGameView
        parent: abstract_view2
        arguments:
            - '@schedule_finder_2016'

    # ===============================================================
    # Schedule Team
    schedule_team_search_form_2016:
        class:  AppBundle\Action\Schedule2016\Team\ScheduleTeamSearchForm
        parent: abstract_form
        arguments:
            - '%project_choices%'
            - '%projects%'
            - '@schedule_finder_2016'

    schedule_team_controller_2016:
        class:  AppBundle\Action\Schedule2016\Team\ScheduleTeamController
        parent: abstract_controller
        arguments:
            - '@schedule_team_search_form_2016'
            - '@schedule_finder_2016'

    schedule_team_view_html_2016:
        class:  AppBundle\Action\Schedule2016\Team\ScheduleTeamView
        parent: abstract_view2
        arguments:
            - '@schedule_team_search_form_2016'
            - '@schedule_finder_2016'
