services:

    schedule_finder_2016:
        class: AppBundle\Action\Schedule2016\ScheduleFinder
        arguments:
            - '@doctrine.dbal.ng2016games_connection' # gameConn
            - '@doctrine.dbal.ng2016games_connection' # regTeamConn

    schedule_template_2016:
        class: AppBundle\Action\Schedule2016\ScheduleTemplate
        calls: [['setContainer', ['@service_container']]]

    schedule_template_show_officials_2016:
        class: AppBundle\Action\Schedule2016\ScheduleTemplate
        calls: [['setContainer', ['@service_container']]]
        arguments: [true]

    # ===============================================================
    # Schedule Game
    schedule_game_search_form_2016:
        class:  AppBundle\Action\Schedule2016\Game\ScheduleGameSearchForm
        parent: abstract_form
        arguments:
            - '%project_choices%'
            - '%projects%'

    schedule_game_controller_2016:
        class:  AppBundle\Action\Schedule2016\Game\ScheduleGameController
        parent: abstract_controller
        arguments:
            - '@schedule_game_search_form_2016'
            - '@schedule_finder_2016'
            - '%project_choices%'
            - '%projects%'

    schedule_game_view_html_2016:
        class:  AppBundle\Action\Schedule2016\Game\ScheduleGameView
        parent: abstract_view2
        arguments:
            - '@schedule_game_search_form_2016'
            - '@schedule_template_2016'

    schedule_game_writer_excel:
        class:  AppBundle\Action\Schedule2016\Game\ScheduleGameWriterExcel

    schedule_game_view_xls_2016:
        class:  AppBundle\Action\Schedule2016\Game\ScheduleGameViewFile
        parent: abstract_view2
        arguments:
            - '@abstract_exporter_xls'
            
    schedule_game_view_csv_2016:
        class:  AppBundle\Action\Schedule2016\Game\ScheduleGameViewFile
        parent: abstract_view2
        arguments:
            - '@abstract_exporter_csv'
            
    schedule_game_view_txt_2016:
        class:  AppBundle\Action\Schedule2016\Game\ScheduleGameViewFile
        parent: abstract_view2
        arguments:
            - '@abstract_exporter_txt'

    # ===============================================================
    # Schedule Official

    schedule_official_search_form_2016:
        class:  AppBundle\Action\Schedule2016\Official\ScheduleOfficialSearchForm
        parent: abstract_form
        arguments:
            - '%project_choices%'
            - '%projects%'

    schedule_official_controller_2016:
        class:  AppBundle\Action\Schedule2016\Official\ScheduleOfficialController
        parent: abstract_controller
        arguments:
            - '@schedule_official_search_form_2016'
            - '@schedule_finder_2016'
            - '%project_choices%'
            - '%projects%'

    schedule_official_view_html_2016:
        class:  AppBundle\Action\Schedule2016\Official\ScheduleOfficialView
        parent: abstract_view2
        arguments:
            - '@schedule_official_search_form_2016'
            - '@schedule_template_show_officials_2016'

    schedule_official_view_xls_2016:
        class:  AppBundle\Action\Schedule2016\Official\ScheduleOfficialViewFile
        parent: abstract_view2
        arguments:
            - '@abstract_exporter_xls'

    schedule_official_view_txt_2016:
        class:  AppBundle\Action\Schedule2016\Official\ScheduleOfficialViewFile
        parent: abstract_view2
        arguments:
            - '@abstract_exporter_txt'

    # ===============================================================
    # Schedule Team
    schedule_team_search_form_2016:
        class:  AppBundle\Action\Schedule2016\Team\ScheduleTeamSearchForm
        parent: abstract_form
        arguments:
            - '%project_choices%'
            - '%projects%'
            - '@schedule_finder_2016'

    schedule_team_controller_2016:
        class:  AppBundle\Action\Schedule2016\Team\ScheduleTeamController
        parent: abstract_controller
        arguments:
            - '@schedule_team_search_form_2016'
            - '@schedule_finder_2016'
            - '%project_choices%'
            - '%projects%'

    schedule_team_view_html_2016:
        class:  AppBundle\Action\Schedule2016\Team\ScheduleTeamView
        parent: abstract_view2
        arguments:
            - '@schedule_team_search_form_2016'
            - '@schedule_template_2016'

    schedule_team_view_xls_2016:
        class:  AppBundle\Action\Schedule2016\Team\ScheduleTeamViewFile
        parent: abstract_view2
        arguments:
            - '@abstract_exporter_xls'
            
    schedule_team_view_csv_2016:
        class:  AppBundle\Action\Schedule2016\Team\ScheduleTeamViewFile
        parent: abstract_view2
        arguments:
            - '@abstract_exporter_csv'

    schedule_team_view_txt_2016:
        class:  AppBundle\Action\Schedule2016\Team\ScheduleTeamViewFile
        parent: abstract_view2
        arguments:
            - '@abstract_exporter_txt'
            
