# Project Person Admin Services
services:

    project_person_repository_v2:
        class: AppBundle\Action\Project\Person\ProjectPersonRepositoryV2
        arguments:
            - '@project_person_connection'

    # reg stands for registered
    reg_person_import_sombero_command:
        class: AppBundle\Action\Project\Person\Admin\Sombero\ImportSomberoCommand
        tags: [{ name: console.command }]
        arguments:
            - '@user_manager'
            - '@project_person_connection'
            - '@project_person_repository_v2'
            - '@cerad.ayso.finder'
            - '@phone_transformer'

    reg_person_manage_roles_command:
        class: AppBundle\Action\Project\Person\Admin\ManageRoles\ManageRolesCommand
        tags: [{ name: console.command }]
        arguments:
            - '@project_person_connection'

# ==========================================================================
# Listing (List throws exception)

    project_person_admin_listing_search_form:
        class:  AppBundle\Action\Project\Person\Admin\Listing\AdminListingSearchForm
        parent: abstract_form
        arguments: ['%project_choices%']

    project_person_admin_listing_controller:
        class:  AppBundle\Action\Project\Person\Admin\Listing\AdminListingController
        parent: abstract_controller
        arguments:
            - '@project_person_repository_v2'
            - '@project_person_admin_listing_search_form'

    project_person_admin_listing_view_html:
        class:  AppBundle\Action\Project\Person\Admin\Listing\AdminListingView
        parent: abstract_view2
        arguments:
            - '@project_person_repository_v2'
            - '@user_repository'
            - '@project_person_admin_listing_search_form'
            - '@project_person_view_decorator'
            - '@project_person_admin_view_filters'
    
    project_person_admin_listing_view_xls:
        class: AppBundle\Action\Project\Person\Admin\Listing\AdminListingViewFile
        parent: abstract_view
        arguments:
            - '@project_person_view_decorator'
            - '@abstract_exporter_xls'
            - '@project_person_admin_view_filters'

    project_person_admin_listing_view_csv:
        class: AppBundle\Action\Project\Person\Admin\Listing\AdminListingViewFile
        parent: abstract_view
        arguments:
            - '@project_person_view_decorator'
            - '@abstract_exporter_csv'
            - '@project_person_admin_view_filters'

# ==========================================================================
# Update

    project_person_admin_update_form:
        class:  AppBundle\Action\Project\Person\Admin\Update\AdminUpdateForm
        parent: abstract_form
        arguments:
            - '%app_project_controls%'
            - '%app_project_registration_form_controls%'
            - '@project_person_view_decorator'
            - '@user_repository'

    project_person_admin_update_controller:
        class:  AppBundle\Action\Project\Person\Admin\Update\AdminUpdateController
        parent: abstract_controller
        arguments:
            - '@project_person_repository_v2'
            - '@project_person_admin_update_form'

    project_person_admin_update_view:
        class:  AppBundle\Action\Project\Person\Admin\Update\AdminUpdateView
        parent: abstract_view2
        arguments:
            - '@project_person_admin_update_form'

# ==========================================================================
# Filters

    project_person_admin_view_filters:
        class:  AppBundle\Action\Project\Person\Admin\AdminViewFilters
        arguments:
            - '@project_person_view_decorator'
            - '@project_person_repository_v2'
            