# Project Person Admin Services
services:

    project_person_repository_v2:
        class: AppBundle\Action\Project\Person\ProjectPersonRepositoryV2
        arguments:
            - '@project_person_connection'

    # reg stands for registered
    reg_person_import_sombero_command:
        class: AppBundle\Action\Project\Person\Admin\Sombero\ImportSomberoCommand
        tags: [{ name: console.command }]
        arguments:
            - '@user_manager'
            - '@project_person_connection'
            - '@project_person_repository_v2'
            - '@ayso_repository'
            - '@phone_transformer'

# ==========================================================================
# Listing (List throws exception)

    project_person_admin_listing_search_form:
        class:  AppBundle\Action\Project\Person\Admin\Listing\AdminListingSearchForm
        parent: abstract_form
        arguments: ['%project_choices%']

    project_person_admin_listing_controller:
        class:  AppBundle\Action\Project\Person\Admin\Listing\AdminListingController
        parent: abstract_controller
        arguments:
            - '@project_person_repository_v2'
            - '@project_person_admin_listing_search_form'

    project_person_admin_listing_view:
        class:  AppBundle\Action\Project\Person\Admin\Listing\AdminListingView
        parent: abstract_view2
        arguments:
            - '@project_person_repository_v2'
            - '@user_repository'
            - '@project_person_admin_listing_search_form'
            - '@project_person_view_decorator'

# ==========================================================================
# Update

    project_person_admin_update_form:
        class:  AppBundle\Action\Project\Person\Admin\Update\AdminUpdateForm
        parent: abstract_form

    project_person_admin_update_controller:
        class:  AppBundle\Action\Project\Person\Admin\Update\AdminUpdateController
        parent: abstract_controller
        arguments:
            - '@project_person_repository_v2'
            - '@project_person_admin_update_form'

    project_person_admin_update_view:
        class:  AppBundle\Action\Project\Person\Admin\Update\AdminUpdateView
        parent: abstract_view2
        arguments:
            - '@project_person_repository_v2'
            - '@user_repository'
            - '@project_person_admin_update_form'
            - '@project_person_view_decorator'
