# Project Person Admin Services
services:

    project_person_repository_v2:
        class: AppBundle\Action\Project\Person\ProjectPersonRepositoryV2
        arguments:
            - '@project_person_connection'

# ==========================================================================
# Listing (List throws exception)

    project_person_admin_listing_search_form:
        class:  AppBundle\Action\Project\Person\Admin\Listing\AdminListingSearchForm
        parent: abstract_form
        arguments: ['%project_choices%']

    project_person_admin_listing_controller:
        class:  AppBundle\Action\Project\Person\Admin\Listing\AdminListingController
        parent: abstract_controller
        arguments:
            - '@project_person_repository_v2'
            - '@project_person_admin_listing_search_form'

    project_person_admin_listing_view_html:
        class:  AppBundle\Action\Project\Person\Admin\Listing\AdminListingView
        parent: abstract_view2
        arguments:
            - '@project_person_repository_v2'
            - '@user_repository'
            - '@project_person_admin_listing_search_form'
            - '@project_person_view_decorator'
    
    project_person_admin_listing_view_xls:
        class: AppBundle\Action\Project\Person\Admin\Listing\AdminListingViewFile
        parent: abstract_view
        arguments:
            - '@project_person_view_decorator'
            - '@abstract_exporter_xls'

    project_person_admin_listing_view_csv:
        class: AppBundle\Action\Project\Person\Admin\Listing\AdminListingViewFile
        parent: abstract_view
        arguments:
            - '@project_person_view_decorator'
            - '@abstract_exporter_csv'

# ==========================================================================
# Listing Unverified (List throws exception)

    project_person_admin_listing_unverified_search_form:
        class:  AppBundle\Action\Project\Person\Admin\ListingUnverified\AdminListingUnverifiedSearchForm
        parent: abstract_form
        arguments: ['%project_choices%']

    project_person_admin_listing_unverified_controller:
        class:  AppBundle\Action\Project\Person\Admin\ListingUnverified\AdminListingUnverifiedController
        parent: abstract_controller
        arguments:
            - '@project_person_repository_v2'
            - '@project_person_admin_listing_unverified_search_form'

    project_person_admin_listing_unverified_view_html:
        class:  AppBundle\Action\Project\Person\Admin\ListingUnverified\AdminListingUnverifiedView
        parent: abstract_view2
        arguments:
            - '@project_person_repository_v2'
            - '@user_repository'
            - '@project_person_admin_listing_unverified_search_form'
            - '@project_person_view_decorator'
    
    project_person_admin_listing_unverified_view_xls:
        class: AppBundle\Action\Project\Person\Admin\ListingUnverified\AdminListingUnverifiedViewFile
        parent: abstract_view
        arguments:
            - '@project_person_view_decorator'
            - '@abstract_exporter_xls'

    project_person_admin_listing_unverified_view_csv:
        class: AppBundle\Action\Project\Person\Admin\ListingUnverified\AdminListingUnverifiedViewFile
        parent: abstract_view
        arguments:
            - '@project_person_view_decorator'
            - '@abstract_exporter_csv'

# ==========================================================================
# Update

    project_person_admin_update_form:
        class:  AppBundle\Action\Project\Person\Admin\Update\AdminUpdateForm
        parent: abstract_form

    project_person_admin_update_controller:
        class:  AppBundle\Action\Project\Person\Admin\Update\AdminUpdateController
        parent: abstract_controller
        arguments:
            - '@project_person_repository_v2'
            - '@project_person_admin_update_form'

    project_person_admin_update_view:
        class:  AppBundle\Action\Project\Person\Admin\Update\AdminUpdateView
        parent: abstract_view2
        arguments:
            - '@project_person_repository_v2'
            - '@user_repository'
            - '@project_person_admin_update_form'
            - '@project_person_view_decorator'
