services:

    cerad.ayso.connection:
        alias: doctrine.dbal.ayso_connection

    cerad.noc.connection:
        alias: doctrine.dbal.noc2018_connection

    cerad.noc.games.connection:
        alias: doctrine.dbal.noc2018games_connection

    cerad.ayso.finder:
        class: Cerad\Bundle\AysoBundle\AysoFinder
        arguments: ['@cerad.ayso.connection']

#    ayso_load_eayso_command:
#        class: AppBundle\Action\Physical\Ayso\Load\AysoLoadCommand
#        tags: [{ name: console.command }]
#        arguments:
#            - '@ayso_connection'

#    cerad.ayso.load_certs.command:
#        class: AysoBundle\Load\LoadCertBSCommand
#        tags: [{ name: console.command }]
#        arguments: ['@cerad.ayso.connection']

#    cerad.ayso.load_vols.command:
#        class: AysoBundle\Load\LoadVolsBSCommand
#        tags: [{ name: console.command }]
#        arguments: ['@cerad.ayso.connection']

#    ayso_load_orgs_command:
#        class: AppBundle\Action\Physical\Ayso\Load\LoadOrgsCommand
#        tags: [{ name: console.command }]
#        arguments: ['@ayso_connection']

    ayso_load_bs_command:
        class: AysoBundle\Load\AysoBSLoadCommand
        tags: [{ name: console.command }]
        arguments:
            - '@cerad.ayso.connection'
            - '@cerad.noc.connection'
            - '%app_project%'

    affinity_transform_command:
        class: AysoBundle\Load\AffinityLoadCommand
        tags: [{ name: console.command }]
        arguments:
            - '%app_project%'
            - '%app_project_venue_name%'
            - '@cerad.noc.games.connection'

    cerad.ayso.region_key_transformer:
        class:  Cerad\Bundle\AysoBundle\DataTransformer\RegionKeyTransformer

    cerad.ayso.volunteer_key_transformer:
        class:  Cerad\Bundle\AysoBundle\DataTransformer\VolunteerKeyTransformer

    cerad.ayso.region_to_sar_transformer:
        class:  Cerad\Bundle\AysoBundle\DataTransformer\RegionToSarTransformer
        arguments: ['@cerad.ayso.finder']