services:

    app_kernel_listener:
        class:  AppBundle\Listener\KernelListener
        calls: [[setContainer, ['@service_container']]]
        tags:  [{ name: kernel.event_subscriber }]

    app_base_template:
        class: AppBundle\Action\BaseTemplate
        calls:
           - ['setRouter',  ['@router']]
           - ['setSecurity',['@security.token_storage','@security.authorization_checker']]
           - ['setProject', ['%app_project%']]

    app_page_template:
        abstract: true
        calls:
           - ['setRouter',  ['@router']]
           - ['setSecurity',['@security.token_storage','@security.authorization_checker']]
           - ['setBaseTemplate', ['@app_base_template']]
           - ['setProject', ['%app_project%']]

    app_action_abstract_controller:
        abstract: true
        calls: [[setContainer, ['@service_container']]]

    # action index
    app_action_index_controller:
        class: AppBundle\Action\Index\IndexController
        parent: app_action_abstract_controller

    # action welcome
    app_action_welcome_controller:
        class: AppBundle\Action\Welcome\WelcomeController
        parent: app_action_abstract_controller
        arguments:
            - '@app_action_welcome_page_template'
            - '@user_login_form'

    app_action_welcome_page_template:
        class: AppBundle\Action\Welcome\WelcomePageTemplate
        parent: app_page_template

    # action home
    app_action_home_controller:
        class: AppBundle\Action\Home\HomeController
        parent: app_action_abstract_controller

    # action admin
    app_action_admin_controller:
        class: AppBundle\Action\Admin\AdminController
        parent: app_action_abstract_controller
        arguments:
          - '@app_action_admin_page_template'
        
    app_action_admin_page_template:
        class: AppBundle\Action\Admin\AdminPageTemplate
        parent: app_page_template


