services:

    app_kernel_listener:
        class:  AppBundle\Listener\KernelListener
        calls: [[setContainer, ['@service_container']]]
        tags:  [{ name: kernel.event_subscriber }]

    app_base_template:
        class: AppBundle\Action\BaseTemplate
        calls:
           - ['setRouter',  ['@router']]
           - ['setSecurity',['@security.token_storage','@security.authorization_checker']]
           - ['setProject', ['%app_project%']]

    app_page_template: # Depreciated
        abstract: true
        calls:
           - ['setRouter',  ['@router']]
           - ['setSecurity',['@security.token_storage','@security.authorization_checker']]
           - ['setBaseTemplate', ['@app_base_template']]
           - ['setProject', ['%app_project%']]

    abstract_form:
        abstract: true
        calls:
           - ['setRouter',  ['@router']]

    abstract_view:
        abstract: true
        calls:
           - ['setRouter',  ['@router']]
           - ['setSecurity',['@security.token_storage','@security.authorization_checker']]
           - ['setBaseTemplate', ['@app_base_template']]
           - ['setProject', ['%app_project%']]

    app_action_abstract_controller: # depreciated
        abstract: true
        calls: [[setContainer, ['@service_container']]]

    abstract_controller:
        abstract: true
        calls: [[setContainer, ['@service_container']]]

    # action index
    app_action_index_controller:
        class: AppBundle\Action\Index\IndexController
        parent: app_action_abstract_controller

    # action welcome
    welcome_controller:
        class:  AppBundle\Action\Welcome\WelcomeController
        parent: abstract_controller

    welcome_view:
        class: AppBundle\Action\Welcome\WelcomeView
        parent: abstract_view
        arguments:
            - '@user_login_form'
            - '@router'

    # action home
    home_controller:
        class:  AppBundle\Action\Home\HomeController
        parent: abstract_controller

    home_view:
        class: AppBundle\Action\Home\HomeView
        parent: abstract_view

    # action admin
    app_action_admin_controller:
        class:  AppBundle\Action\Admin\AdminController
        parent: abstract_controller
        arguments:
          - '@app_action_admin_page_template'
        
    app_action_admin_page_template:
        class: AppBundle\Action\Admin\AdminPageTemplate
        parent: app_page_template


