services:

    project_connection:
        alias: doctrine.dbal.project_connection

    project_factory:
        class: AppBundle\Action\Project\ProjectFactory

    project_person_repository:
        class: AppBundle\Action\Project\Person\ProjectRersonRepository
        arguments: ['@user_connection','@project_factory']
