services:

    app_points_calculator:
        class: AppBundle\Action\Results\PoolPlay\Calculator\PointsCalculator

    app_standings_calculator:
        class: AppBundle\Action\Results\PoolPlay\Calculator\StandingsCalculator
        arguments: ['@project_factory']

    app_sportsmanship_calculator:
        class: AppBundle\Action\Results\Sportsmanship\Calculator\SportsmanshipCalculator

    app_final_calculator:
        class: AppBundle\Action\Results\FinalStandings\Calculator\FinalCalculator
        arguments: ['@project_factory']

    app_action_results_repository:
        class: AppBundle\Action\Schedule\ScheduleRepository
        arguments: ['@project_connection']

    results_poolplay_controller:
        class: AppBundle\Action\Results\PoolPlay\ResultsPoolPlayController
        parent: app_action_abstract_controller

    results_poolplay_view_html:
        class: AppBundle\Action\Results\PoolPlay\ResultsPoolPlayView
        parent: abstract_view
        arguments:
            - '@app_action_schedule_repository'
            - '@app_standings_calculator'

    results_medalround_controller:
        class: AppBundle\Action\Results\MedalRound\ResultsMedalRoundController
        parent: app_action_abstract_controller

    results_medalround_view_html:
        class: AppBundle\Action\Results\MedalRound\ResultsMedalRoundView
        parent: abstract_view
        arguments:
            - '@app_action_schedule_repository'
            - '@app_standings_calculator'

    results_final_controller:
        class: AppBundle\Action\Results\FinalStandings\ResultsFinalController
        parent: app_action_abstract_controller

    results_final_view_html:
        class: AppBundle\Action\Results\FinalStandings\ResultsFinalView
        parent: abstract_view
        arguments:
            - '@app_action_schedule_repository'
            - '@app_final_calculator'

    results_sportsmanship_controller:
        class: AppBundle\Action\Results\Sportsmanship\ResultsSportsmanshipController
        parent: app_action_abstract_controller

    results_sportsmanship_view_html:
        class: AppBundle\Action\Results\Sportsmanship\ResultsSportsmanshipView
        parent: abstract_view
        arguments:
            - '@app_action_schedule_repository'
            - '@app_sportsmanship_calculator'
