services:

    app_action_results_repository:
        class: AppBundle\Action\Schedule\ScheduleRepository
        arguments: ['@doctrine.dbal.project_connection']

    app_action_results_poolplay_controller:
        class: AppBundle\Action\Results\PoolPlay\ResultsPoolPlayController
        parent: app_action_abstract_controller
        arguments:
            - '@app_action_schedule_repository'
