services:

    app_action_schedule_repository:
        class: AppBundle\Action\Schedule\ScheduleRepository
        arguments: ['@doctrine.dbal.project_connection']

    schedule_team_controller:
        class: AppBundle\Action\Schedule\Team\ScheduleTeamController
        parent: app_action_abstract_controller
        arguments:
            - '@app_action_schedule_repository'

    schedule_team_view_html:
        class: AppBundle\Action\Schedule\Team\ScheduleTeamView
        parent: abstract_view
        arguments:
            - '@app_action_schedule_repository'

    schedule_team_view_csv:
        class: AppBundle\Action\Schedule\Team\ScheduleTeamViewCsv
        parent: abstract_view
        arguments:
            - '@app_action_schedule_repository'

    schedule_team_view_xls:
        class: AppBundle\Action\Schedule\Team\ScheduleTeamViewXls
        parent: abstract_view
        arguments:
            - '@app_action_schedule_repository'

    schedule_game_controller:
        class: AppBundle\Action\Schedule\Game\ScheduleGameController
        parent: app_action_abstract_controller
        arguments:
            - '@app_action_schedule_repository'

    schedule_game_view_html:
        class: AppBundle\Action\Schedule\Game\ScheduleGameView
        parent: abstract_view
        arguments:
            - '@app_action_schedule_repository'

    schedule_game_view_csv:
        class: AppBundle\Action\Schedule\Game\ScheduleGameViewCsv
        parent: abstract_view
        arguments:
            - '@app_action_schedule_repository'

    schedule_game_view_xls:
        class: AppBundle\Action\Schedule\Game\ScheduleGameViewXls
        parent: abstract_view
        arguments:
            - '@app_action_schedule_repository'

    schedule_game_view_core:
        class: AppBundle\Action\Schedule\Game\ScheduleGameViewCore
        parent: abstract_view
        arguments:
            - '@app_action_schedule_repository'

    schedule_game_view_extra:
        class: AppBundle\Action\Schedule\Game\ScheduleGameViewExtra
        parent: abstract_view
        arguments:
            - '@app_action_schedule_repository'

