services:

    app_action_schedule_repository:
        class: AppBundle\Action\Schedule\ScheduleRepository
        arguments: ['@doctrine.dbal.project_connection']

    app_action_schedule_team_controller:
        class: AppBundle\Action\Schedule\Team\ScheduleTeamController
        parent: app_action_abstract_controller
        arguments:
            - '@app_action_schedule_repository'

    app_action_schedule_game_controller:
        class: AppBundle\Action\Schedule\Game\ScheduleGameController
        parent: app_action_abstract_controller
        arguments:
            - '@app_action_schedule_repository'
