imports:
    - { resource: parameters.yml }
    - { resource: doctrine.yml   }
    - { resource: security.yml   }
    - { resource: services.yml   }
#    - { resource: '@CeradAysoBundle/services.yml' }
    - { resource: users.yml      }
    - { resource: providers.yml  }
    - { resource: projects.yml }
    - { resource: projects/AYSONationalGames2019.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    app_version: '2019.04.22.00'

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: false }
    #serializer:      { enable_annotations: true }
    #templating:
    #    engines: ['php']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    session:
        handler_id:  session.handler.native_file
# save_path in project path causes 500 Internal Server Error - ContextErrorException: Warning: SessionHandler::read(): Session data file is not created by your uid
# set save_path in parameters.yml
#        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
        name:        zayso_session
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
#twig:
#    debug:            "%kernel.debug%"
#    strict_variables: "%kernel.debug%"
#    paths:
#        "%kernel.root_dir%/../src/AppBundle/Action":  App
#        "%kernel.root_dir%/../src/UserBundle/Action": CeradUser

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"

    disable_delivery: '%mailer_disable_delivery%'
    spool: { type: memory }

#   spool:     { type: memory } # Commented out for monolog email
#   spool: { type: file, path: %kernel.root_dir%/../var/spool }
