
# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8
            ayso:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name_ayso%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8
            test:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name_test%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8
            ng2014:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name_ng2014%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8
            ng2014games:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name_ng2014games%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8
            ng2016:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name_ng2016%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8

    orm:
        default_entity_manager:       default
        auto_generate_proxy_classes: %kernel.debug%
                
        entity_managers:
          
            default:
                connection: default
                mappings:
                    #CeradOrgBundle:    ~
                    #CeradUserBundle:   ~
                    #CeradPersonBundle: ~

            #users:
            #   connection: users
            #   mappings:
            #        CeradUserBundle: ~
                        
                       