# Pretend that this is a database and the app supports multiple projects
parameters:

    project_choices:
        NG2016 : AYSONationalGames2016
        NG2014 : AYSONationalGames2014

    projects:

        AYSONationalGames2016:
            programs:
                Core: Core
                VIP:  VIP
            dates: # Left is label, right is value
                Wed: '2016-07-06' # Wed Soccerfest
                Thu: '2016-07-07' # Thu Pool Play
                Fri: '2016-07-08' # Fri Pool Play
                Sat: '2016-07-09' # Sat Pool Play and Quarter Finals
                Sun: '2016-07-10' # Sun Semi and Finals
            genders:
                B:  B
                G:  G
            ages:
                U10: U10
                U12: U12
                U14: U14
                U16: U16
                U19: U19

        AYSONationalGames2014:
            programs:
                Core:  Core
                Extra: Extra
                VIP:   VIP
            dates:
                Wed: '2014-07-02' # Wed Soccerfest
                Thu: '2014-07-03' # Thu Pool Play
                Fri: '2014-07-04' # Fri Pool Play
                Sat: '2014-07-05' # Sat Pool Play and Quarter Finals
                Sun: '2014-07-06' # Sun Semi and Finals
            genders:
                B:  B
                G:  G
            ages:
                U10: U10
                U12: U12
                U14: U14
                U16: U16
                U19: U19
