
app_user:
    resource: "@AppBundle/Action/Project/User/routes.yml"
    prefix: /user

app_game:
    resource: "@AppBundle/Resources/config/routes/game.yml"
    prefix: /game

app_schedule:
    resource: "@AppBundle/Resources/config/routes/schedule.yml"
    prefix: /schedule

app_results:
    resource: "@AppBundle/Resources/config/routes/results.yml"
    prefix: /results

app_project_person:
    resource: "@AppBundle/Action/Project/Person/routes.yml"
    prefix: /project/person

app_app:
    resource: "@AppBundle/Action/App/routes.yml"
    prefix: /
