
app_user:
    resource: "@AppBundle/Action/Project/User/routes.yml"
    prefix: /user

app_game:
    resource: "@AppBundle/Action/Game/routes.yml"
    prefix: /game

app_game_report:
    resource: "@AppBundle/Action/GameReport2016/routes.yml"
    prefix: /game/report

app_game_official:
    resource: "@AppBundle/Action/GameOfficial/config/routes.yml"
    prefix: /game/official

app_schedule_2016:
    resource: "@AppBundle/Action/Schedule2016/routes.yml"
    prefix: /schedule

app_results_2016:
    resource: "@AppBundle/Action/Results2016/routes.yml"
    prefix: /results

app_project_person:
    resource: "@AppBundle/Action/Project/Person/routes.yml"
    prefix: /project/person

app_reg_person:
    resource: "@AppBundle/Action/RegPerson/config/routes.yml"
    prefix: /project/person

app_project_person_admin:
    resource: '@AppBundle/Action/Project/Person/Admin/routes.yml'
    prefix: /project/person/admin

app_regteam_2016:
    resource: "@AppBundle/Action/RegTeam/config/routes.yml"
    prefix: /regteam

app_app:
    resource: "@AppBundle/Action/App/routes.yml"
    prefix: /
    
#   must load last
app_mystery_routes:
    resource: "@AppBundle/Action/App/mystery_routes.yml"
    prefix: /