
app_user:
    resource: "@AppBundle/Action/Project/User/routes.yml"
    prefix: /user

app_game:
    resource: "@AppBundle/Action/Game/routes.yml"
    prefix: /game

app_game_report:
    resource: "@AppBundle/Action/GameReport2016/routes.yml"
    prefix: /game/report

app_schedule:
    resource: "@AppBundle/Action/Schedule/routes.yml"
    prefix: /schedule

schedule_2016:
    resource: "@AppBundle/Action/Schedule2016/routes.yml"
    prefix: /schedule2016

app_results:
    resource: "@AppBundle/Action/Results/routes.yml"
    prefix: /results

app_results_2016:
    resource: "@AppBundle/Action/Results2016/routes.yml"
    prefix: /results2016

app_project_person:
    resource: "@AppBundle/Action/Project/Person/routes.yml"
    prefix: /project/person

app_project_person_admin:
    resource: '@AppBundle/Action/Project/Person/Admin/routes.yml'
    prefix: /project/person/admin

app_app:
    resource: "@AppBundle/Action/App/routes.yml"
    prefix: /
