parameters:
    users:
        refereex:
            id:    -1
            name:  Referee
            role:  ROLE_REFEREE
            email: referee@fake.com
        assignorx:
            id:    -2
            name:  Assignor
            role:  ROLE_ASSIGNOR
            email: assignor@fake.com
        scorerx:
            id:    -3
            name:  Scorer
            role:  ROLE_SCORE_ENTRY
            email: scorer@fake.com
        userx:
            id:    -4
            name:  User
            role:  ROLE_USER
            email: user@fake.com
        staffx:
            id:    -5
            name:  Staff
            role:  ROLE_STAFF
            email: staff@fake.com
        admin:
            id:    -6
            name:  Admin
            role:  ROLE_ADMIN
            email: admin@fake.com
