services:

    project_connection:
        alias: doctrine.dbal.ng2019_connection

    project_factory:
        class: AppBundle\Action\Project\ProjectFactory

    project_person_repository:
        class: AppBundle\Action\Project\Person\ProjectRersonRepository
        arguments: ['@project_connection','@project_factory']
