services:

    _defaults: { public: true }

    project_connection:
        alias: doctrine.dbal.ng2019_connection

    project_factory:
        public: true
        class: AppBundle\Action\Project\ProjectFactory

    project_person_repository:
        public: true
        class: AppBundle\Action\Project\Person\ProjectRersonRepository
        arguments: ['@project_connection','@project_factory']

#    project_migrate_command:
#        class: AppBundle\Action\Project\Migrate\ProjectMigrateCommand
#        tags: [{ name: console.command }]
#        arguments:
#            - '@doctrine.dbal.ng2014_connection'
#            - '@doctrine.dbal.ng2019_connection'
#
