regteam_export:
    path: /export
    defaults:
        _controller:    regteam_export_controller
        _view:          regteam_export_xls
        _rolex:         ROLE_ADMIN

regteam_import:
    path: /import
    defaults:
        _controller:    regteam_import_controller
        _view:          regteam_import_view
        _rolex:         ROLE_ADMIN
