regteam_export:
    path: /export
    defaults:
        _controller:    regteam_export_controller
        _view:          regteam_export_xls
        _role:          ROLE_ADMIN

regteam_import:
    path: /import
    defaults:
        _controller:    regteam_import_controller
        _view:          regteam_import_view
        _role:          ROLE_ADMIN

regteam_transform:
    path: /transform
    defaults:
        _controller:    reg_team_transform_controller
        _view:          reg_team_transform_view
        _role:          ROLE_ADMIN
