services:

    # ===============================================================
    # Team Management
    regteam_upload_form:
        class:  AppBundle\Action\RegTeam\RegTeamUploadForm
        parent: abstract_form
        arguments:
            - '@regteam_import_xls'
            
    regteam_import_controller:
        class:  AppBundle\Action\RegTeam\RegTeamImportController
        parent: abstract_controller
        arguments:
            - '@regteam_upload_form'
            - '%project_choices%'
            - '%projects%'
            - '@reg_team_updater'

    regteam_import_view:
        class:  AppBundle\Action\RegTeam\RegTeamImportView
        parent: abstract_view2
        arguments:
            - '@regteam_upload_form'

    regteam_export_controller:
        class:  AppBundle\Action\RegTeam\RegTeamExportController
        parent: abstract_controller
        arguments:
            - '@game_finder'
            - '%project_choices%'
            - '%projects%'

    regteam_export_xls:
        class:  AppBundle\Action\RegTeam\RegTeamExcelWriter
        parent: abstract_view2
        arguments:
            - '@abstract_exporter_xls'

    abstract_importer_xls:
        class: AppBundle\Action\AbstractImporter

    regteam_import_xls:
        class:  AppBundle\Action\RegTeam\RegTeamFileReader
        parent: abstract_importer_xls

    reg_team_updater:
        class: AppBundle\Action\RegTeam\RegTeamUpdater
        arguments:
            - '@reg_team_connection'

    # ===========================================
    # Transform the team regstrar's spreadsheet to out spreadsheet
    reg_team_transform_form:
        class:  AppBundle\Action\RegTeam\Transform\RegTeamTransformForm
        parent: abstract_form

    reg_team_transform_reader_excel:
        class:  AppBundle\Action\RegTeam\Transform\RegTeamTransformReaderExcel
        arguments:
            - '@ayso_repository'

    reg_team_transform_writer_excel:
        class:  AppBundle\Action\RegTeam\Transform\RegTeamTransformWriterExcel

    reg_team_transform_controller:
        class:  AppBundle\Action\RegTeam\Transform\RegTeamTransformController
        arguments:
            - '@reg_team_transform_form'
            - '@reg_team_transform_reader_excel'

    reg_team_transform_view:
        class:  AppBundle\Action\RegTeam\Transform\RegTeamTransformView
        parent: abstract_view2
        arguments:
            - '@reg_team_transform_form'
            - '@reg_team_transform_writer_excel'
