services:

    # ===============================================================
    # Team Management
    regteam_upload_form_2016:
        class:  AppBundle\Action\RegTeam\RegTeamUploadForm
        parent: abstract_form
        arguments:
            - '@game_connection'
            
    regteam_controller_2016:
        class:  AppBundle\Action\RegTeam\RegTeamController
        parent: abstract_controller
        arguments:
            - '@game_finder'
            - '@regteam_upload_form_2016'
            - '%project_choices%'
            - '%projects%'

    regteam_view_2016:
        class:  AppBundle\Action\RegTeam\RegTeamView
        parent: abstract_view2
        arguments:
            - '@regteam_upload_form_2016'

    regteam_view_xls_2016:
        class:  AppBundle\Action\RegTeam\RegTeamViewFile
        parent: abstract_view2
        arguments:
            - '@abstract_exporter_xls'
