
app_index:
    path: /
    defaults:
        _controller: app_action_index_controller

app_welcome:
    path: /welcome
    defaults:
        _view:       welcome_view
        _controller: welcome_controller

app_home:
    path: /home
    defaults:
        _role:       ROLE_USER
        _view:       home_view
        _controller: home_controller

app_admin:
    path: /admin
    defaults:
        _controller: app_action_admin_controller
