
app_index:
    path: /
    defaults:
        _controller: app_action_index_controller

app_welcome:
    path: /welcome
    defaults:
        _controller: app_action_welcome_controller

app_home:
    path: /home
    defaults:
        _controller: app_action_home_controller

app_admin:
    path: /admin
    defaults:
        _controller: app_action_admin_controller

cerad_user_login:
    path: /user/login
    defaults:
        _controller: app_action_index_controller
