app_schedule_team:
    path: /schedule/team
    defaults:
        _controller: app_action_schedule_team_controller

app_schedule_game:
    path: /schedule/game
    defaults:
        _controller: app_action_schedule_game_controller
