app_schedule_team:
    path: /team.{_format}
    defaults:
        _format: html
        _controller: schedule_team_controller
        _view_html:  schedule_team_view_html
        _view_xls:   schedule_team_view_xls
        _view_csv:   schedule_team_view_csv
        _view_pdf:   schedule_team_view_pdf
        _view_json:  schedule_team_view_json

app_schedule_game:
    path: /game.{_format}
    defaults:
        _format: html
        _controller: schedule_game_controller
        _view_html:  schedule_game_view_html
        _view_xls:   schedule_game_view_xls
        _view_csv:   schedule_game_view_csv
        _view_pdf:   schedule_game_view_pdf
        _view_json:  schedule_game_view_json
