# User routes
#user_login:
#    path: /login
#    defaults:
#        _controller: index_controller

cerad_user_login_check:
    path:  /login-check

cerad_user_logout:
    path:  /logout

cerad_user_logout:
    path:  /logout

cerad_user_create:
    path: /create
    defaults:
        _view:       user_create_view
        _controller: user_create_controller

cerad_user_update:
    path: /update
    defaults:
        _view:       user_update_view
        _controller: user_update_controller

# user password
cerad_user_password_update:
    path: /password/update
    defaults:
        _controller: user_password_update_controller

cerad_user_password_reset_request:
    path: /password/reset-request
    defaults:
        _view:       user_password_reset_request_view
        _controller: user_password_reset_request_controller

cerad_user_password_reset_response:
    path: /password/reset-response/{token}
    defaults:
        token:       null
        _view:       user_password_reset_response_view
        _controller: user_password_reset_response_controller

# user social network
cerad_user_authen_connect:
    path:  /authen/connect/{providerName}
    defaults:
        _controller: user_authen_connect_controller

verad_user_authen_callback:
    path:  /authen/callback
    defaults:
        _controller: user_authen_callback_controller

