# Reg
reg_person_register:
  path: /register
  defaults:
    _role:       ROLE_USER
    _controller: Zayso\Reg\Person\Register\RegisterAction

reg_person_update:
  path: /update
  defaults:
    _role:       ROLE_USER
    _controller: Zayso\Reg\Person\Register\RegisterAction

reg_person_update_fed: # Is this even used?
  path: /update-fed
  defaults:
    _role:       ROLE_USER
    _controller: Zayso\Reg\Person\Register\RegisterAction

reg_person_persons_update:
  path: /persons/update
  defaults:
    _role:       ROLE_USER
    _view:       reg_person_persons_update_view
    _controller: reg_person_persons_update_controller

reg_person_teams_update:
  path: /teams/update
  defaults:
    _role:       ROLE_USER
    _view:       reg_person_teams_update_view
    _controller: reg_person_teams_update_controller
