# Fed
services:

    _defaults: { autowire: true, autoconfigure: true, public: false }

    Zayso\Reg\:
        resource: './*'
        exclude:  './Person/Register/{*.php}'

    Zayso\Reg\Person\RegPersonConnection: '@doctrine.dbal.reg_person_connection'

    Zayso\Reg\Person\Register\RegPersonRegisterForm:
        arguments:
            $projectControls: '%app_project_controls%'
            $formControls:    '%app_project_registration_form_controls%'
