Cerad\Bundle\UserBundle\Entity\User:
    type:  entity
    table: users
    repositoryClass: Cerad\Bundle\UserBundle\Entity\UserRepository
    
    id:
        id:
            type:   integer
            generator: { strategy: AUTO }
    
    oneToMany:

       authens:
           targetEntity: UserAuthen
           mappedBy:     user
           indexBy:      id
           cascade:      ['all']
           
    fields:
              
        personGuid:
            column:   person_guid
            type:     string
            length:   40
            nullable: true
            
        personStatus:
            column:   person_status
            type:     string
            length:   20
            nullable: true
            
        personVerified:
            column:   person_verified
            type:     string
            length:   20
            nullable: true
            
        personConfirmed:
            column: person_confirmed
            type:   boolean
                        
# ================================================
# These all came from the FOSUserBundle
        username:
            type: string
            
        usernameCanonical:
            column: username_canonical
            type:   string
            unique: true
            
        email:
            type: string
            
        emailCanonical:
            column: email_canonical
            type:   string
            unique: true
            
        emailConfirmed:
            column: email_confirmed
            type:   boolean
            
        salt:
            type: string

        password:
            type: string
            
        passwordHint:
            column:   password_hint
            type:     string
            length:   20
            nullable: true
            
        roles:
            type: array
                    
        # ===============================================
        # Account security stuff
        accountName:
            column:   account_name
            type:     string
            length:   80
            nullable: true
            
        accountEnabled:
            column: account_enabled
            type: boolean
            
        accountLocked:
            column: account_locked
            type:   boolean
            
        accountExpired:
            column: account_expired
            type:   boolean
            
        accountExpiresAt:
            column:   account_expires_at
            type:     datetime
            nullable: true
                    
        # Some logging, also needs to be moved
        accountCreatedOn:
            column:   account_created_on
            type:     datetime
            nullable: true
            
        accountUpdatedOn:
            column:   account_updated_on
            type:     datetime
            nullable: true
            
        accountLastLoginOn:
            column:   account_last_login_on
            type:     datetime
            nullable: true
            
        # To force password resets
        credentialsExpired:
            column: credentials_expired
            type:   boolean
            
        credentialsExpireAt:
            column:   credentials_expire_at
            type:     datetime
            nullable: true
            
        # ===================================================
        # Request Password Reset
        passwordResetToken:
            column:   password_reset_token
            type:     string
            nullable: true
            
        passwordResetRequestedAt:
            column:   password_reset_requested_at
            type:     datetime
            nullable: true
            
        passwordResetRequestExpiresAt:
            column:   password_reset_expires_at
            type:     datetime
            nullable: true
            
        # ===================================================
        # Confirm User Email
        emailConfirmToken:
            column:   email_confirm_token
            type:     string
            nullable: true
            
        emailConfirmRequestedAt:
            column:   email_confirm_requested_at
            type:     datetime
            nullable: true
            
        emailConfirmRequestExpiresAt:
            column:   email_confirm_expires_at
            type:     datetime
            nullable: true
            
        # ===================================================
        # Confirm Person really belongs to account
        personConfirmToken:
            column:   person_confirm_token
            type:     string
            nullable: true
            
        personConfirmRequestedAt:
            column:   person_confirm_requested_at
            type:     datetime
            nullable: true
            
        personConfirmRequestExpiresAt:
            column:   person_confirm_expires_at
            type:     datetime
            nullable: true
