Cerad\Bundle\UserBundle\Entity\UserAuthen:
    type:  entity
    table: user_authens
    
    id:
        id:
            type:   string
            length: 128
            generator: { strategy: NONE }
            
    manyToOne:
      
        user:
            targetEntity: User
            inversedBy:   authens
            
    fields:
        source:
            type:     string
            length:   20
            nullable: false
            
        status:
            type:     string
            length:   20
            nullable: false
          
        profile:
            type:     array
            nullable: true

           