services:

    _defaults: { public: true }

    results_standings_calculator_2016:
        public: true
        class: AppBundle\Action\Results2019\ResultsStandingsCalculator
        arguments:
            - '@game_connection'

    results_finder_2016:
        public: true
        class: AppBundle\Action\Results2019\ResultsFinder
        arguments:
            - '@game_connection'
            - '@results_standings_calculator_2016'

    # ===============================================================
    # Pool Play Results
    results_poolplay_search_form_2016:
        public: true
        class:  AppBundle\Action\Results2019\PoolPlay\ResultsPoolPlaySearchForm
        parent: abstract_form
        arguments:
            - '%project_choices%'
            - '%projects%'
            - '@game_connection'

    results_poolplay_controller_2016:
        public: true
        class:  AppBundle\Action\Results2019\PoolPlay\ResultsPoolPlayController
        parent: abstract_controller
        arguments:
            - '@results_poolplay_search_form_2016'
            - '@results_finder_2016'
            - '%project_choices%'
            - '%projects%'

    results_poolplay_view_html_2016:
        public: true
        class:  AppBundle\Action\Results2019\PoolPlay\ResultsPoolPlayView
        parent: abstract_view2
        arguments:
            - '@results_poolplay_search_form_2016'

    # ===============================================================
    # Medal Round Results
    results_medalround_search_form_2016:
        public: true
        class:  AppBundle\Action\Results2019\MedalRound\ResultsMedalRoundSearchForm
        parent: abstract_form
        arguments:
            - '%project_choices%'
            - '%projects%'
            - '@game_connection'

    results_medalround_controller_2016:
        public: true
        class:  AppBundle\Action\Results2019\MedalRound\ResultsMedalRoundController
        parent: abstract_controller
        arguments:
            - '@results_medalround_search_form_2016'
            - '@results_finder_2016'
            - '%project_choices%'
            - '%projects%'

    results_medalround_view_html_2016:
        public: true
        class:  AppBundle\Action\Results2019\MedalRound\ResultsMedalRoundView
        parent: abstract_view2
        arguments:
            - '@results_medalround_search_form_2016'

    # ===============================================================
    # Sportsmanship Results
    results_sportsmanship_calculator_2016:
        public: true
        class: AppBundle\Action\Results2019\ResultsSportsmanshipCalculator

    results_sportsmanship_search_form_2016:
        public: true
        class:  AppBundle\Action\Results2019\Sportsmanship\ResultsSportsmanshipSearchForm
        parent: abstract_form
        arguments:
            - '%project_choices%'
            - '%projects%'
            - '@game_connection'

    results_sportsmanship_controller_2016:
        public: true
        class:  AppBundle\Action\Results2019\Sportsmanship\ResultsSportsmanshipController
        parent: abstract_controller
        arguments:
            - '@results_sportsmanship_search_form_2016'
            - '@results_finder_2016'
            - '%project_choices%'
            - '%projects%'

    results_sportsmanship_view_html_2016:
        public: true
        class:  AppBundle\Action\Results2019\Sportsmanship\ResultsSportsmanshipView
        parent: abstract_view2
        arguments:
            - '@results_sportsmanship_search_form_2016'
            - '@results_sportsmanship_calculator_2016'
    # ===============================================================
    # Final Results
    results_final_calculator_2016:
        public: true
        class: AppBundle\Action\Results2019\ResultsFinalCalculator

    results_final_search_form_2016:
        public: true
        class:  AppBundle\Action\Results2019\FinalStandings\ResultsFinalSearchForm
        parent: abstract_form
        arguments:
            - '%project_choices%'
            - '%projects%'
            - '@game_connection'

    results_final_controller_2016:
        public: true
        class:  AppBundle\Action\Results2019\FinalStandings\ResultsFinalController
        parent: abstract_controller
        arguments:
            - '@results_final_search_form_2016'
            - '@results_finder_2016'
            - '%project_choices%'
            - '%projects%'

    results_final_view_html_2016:
        public: true
        class:  AppBundle\Action\Results2019\FinalStandings\ResultsFinalView
        parent: abstract_view2
        arguments:
            - '@results_final_search_form_2016'
            - '@results_final_calculator_2016'
