services:

    _defaults: { public: true }

    phone_transformer:
        public: true
        class:  AppBundle\Action\Physical\Person\DataTransformer\PhoneTransformer

    shirt_size_transformer:
        public: true
        class:  AppBundle\Action\Physical\Person\DataTransformer\ShirtSizeTransformer

