services:

    game_official_assign_workflow:
        class: AppBundle\Action\GameOfficial\AssignWorkflow

    game_official_updater:
        class: AppBundle\Action\GameOfficial\GameOfficialUpdater
        arguments:
            - '@game_connection'
            - '@project_person_connection'

    game_official_details_finder:
        class: AppBundle\Action\GameOfficial\GameOfficialDetailsFinder
        arguments:
            - '@game_connection'
            - '@project_person_connection'
            - '@ayso_region_to_sar_transformer'

    game_official_conflicts_finder:
        class: AppBundle\Action\GameOfficial\GameOfficialConflictsFinder
        arguments:
            - '@game_connection'

    game_official_voter:
        class: AppBundle\Action\GameOfficial\GameOfficialVoter
        tags: [{ name: security.voter }]
        arguments:
            - '@game_connection'
            - '@project_person_connection'
            - '@security.access.decision_manager'
            - '@reg_person_finder'

    # =========================================================================
    # Assign by assignee

    game_official_assignee_finder:
        class: AppBundle\Action\GameOfficial\AssignByAssignee\AssigneeFinder
        arguments: ['@project_person_connection','@reg_person_finder']

    game_official_assign_by_assignee_form:
        class:  AppBundle\Action\GameOfficial\AssignByAssignee\AssigneeForm
        parent: abstract_form
        arguments:
            - '@game_official_assign_workflow'
            - '@game_official_assignee_finder'
            - '@game_official_conflicts_finder'
            - '@reg_person_finder'

    game_official_assign_by_assignee_controller:
        class:  AppBundle\Action\GameOfficial\AssignByAssignee\AssigneeController
        parent: abstract_controller
        arguments:
            - '@game_official_assign_by_assignee_form'
            - '@game_finder'
            - '@game_official_updater'

    game_official_assign_by_assignee_view:
        class:  AppBundle\Action\GameOfficial\AssignByAssignee\AssigneeView
        parent: abstract_view2
        arguments:
            - '@game_official_assign_by_assignee_form'

    # =========================================================================
    # Assign by assignor

    game_official_assignor_finder:
        class: AppBundle\Action\GameOfficial\AssignByAssignor\AssignorFinder
        arguments:
            - '@project_person_connection'
            - '@ayso_region_to_sar_transformer'

    game_official_assign_by_assignor_form:
        class:  AppBundle\Action\GameOfficial\AssignByAssignor\AssignorForm
        parent: abstract_form
        arguments:
            - '@game_official_assign_workflow'
            - '@game_official_assignor_finder'
            - '@game_official_conflicts_finder'

    game_official_assign_by_assignor_controller:
        class:  AppBundle\Action\GameOfficial\AssignByAssignor\AssignorController
        parent: abstract_controller
        arguments:
            - '@game_official_assign_by_assignor_form'
            - '@game_finder'
            - '@game_official_updater'

    game_official_assign_by_assignor_view:
        class:  AppBundle\Action\GameOfficial\AssignByAssignor\AssignorView
        parent: abstract_view2
        arguments:
            - '@game_official_assign_by_assignor_form'

    # =========================================================================
    # Export summary report
    game_official_summary_controller:
        class:  AppBundle\Action\GameOfficial\Summary\SummaryController
        parent: abstract_controller
        arguments:
            - '@game_finder'
            - '@reg_person_finder'

    game_official_summary_view:
        class:  AppBundle\Action\GameOfficial\Summary\SummaryViewExcel
        parent: abstract_view2
        arguments:
            - '@game_official_summary_writer_excel'

    game_official_summary_writer_excel:
        class:  AppBundle\Action\GameOfficial\Summary\SummaryWriterExcel

