
app_index:
    path: /
    defaults:
        _controller: index_controller

app_welcome:
    path: /welcome
    defaults:
        _view:       welcome_view
        _controller: welcome_controller

app_home:
    path: /home
    defaults:
        _role:       ROLE_USER
        _view:       home_view
        _controller: home_controller

app_admin:
    path: /admin
    defaults:
        _role:       ROLE_STAFF
        _view:       admin_view
        _controller: admin_controller

app_text_alerts:
    path: /textalerts
    defaults:
        _view:       text_alerts_view
        _controller: text_alerts_controller

rules_of_competition:
    path: /rules
    defaults:
        fileType: pdf # For future use, only pdf is currently supported
        fileName: SAMPLE.2019_National_Games_Governing_Rules.pdf
        _controller: file_controller

detailed_instruction:
    path: /self-assigning
    defaults:
        fileType: pdf # For future use, only pdf is currently supported
        fileName: Referee_Self-Assigning.pdf
        _controller: file_controller

assignor_instruction:
    path: /assigning
    defaults:
        fileType: pdf # For future use, only pdf is currently supported
        fileName: referee_assigning.pdf
        _controller: file_controller
