
app_index:
    path: /
    defaults:
        _controller: index_controller

app_welcome:
    path: /welcome
    defaults:
        _view:       welcome_view
        _controller: welcome_controller

app_home:
    path: /home
    defaults:
        _role:       ROLE_USER
        _view:       home_view
        _controller: home_controller

app_admin:
    path: /admin
    defaults:
        _role:       ROLE_STAFF
        _view:       admin_view
        _controller: admin_controller

#   default path traps
#   must be loaded last

app_images:
    path: /images
    prefix: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /welcome
        permanent: true
        
app_pdf:
    path: /pdf
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /welcome
        permanent: true

app_css:
    path: /css
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /welcome
        permanent: true

app_js:
    path: /js
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /welcome
        permanent: true

