
app_index:
    path: /
    defaults:
        _controller: index_controller

app_welcome:
    path: /welcome
    defaults:
        _view:       welcome_view
        _controller: welcome_controller

app_home:
    path: /home
    defaults:
        _role:       ROLE_USER
        _view:       home_view
        _controller: home_controller

app_admin:
    path: /admin
    defaults:
        _role:       ROLE_STAFF
        _view:       admin_view
        _controller: admin_controller

#   unknown path trap
#   must be loaded last

#app__mystery__url:
#    path: /{url}/
#    defaults:
#        _controller: FrameworkBundle:Redirect:urlRedirect
#        path: /welcome
#        requirements:
#            url: [.*]
