parameters:
    # Eventually want to be able to customize thid
    app_home_route:    app_home
    app_welcome_route: app_welcome

services:

    app_kernel_listener:
        class:  AppBundle\Listener\KernelListener
        calls: [[setContainer, ['@service_container']]]
        tags:  [{ name: kernel.event_subscriber }]
        arguments: ['%secure_routes%']

    app_base_template:
        class: AppBundle\Action\BaseTemplate
        calls:
            - ['setRouter',  ['@router']]
            - ['setSecurity',['@security.token_storage','@security.authorization_checker']]
            - ['setProject', ['%app_project%']]
        arguments:
            - '%show_header_image%'
            - '%show_results_menu%'
            - '%show_final_results%'

    abstract_form:
        abstract: true
        calls:
           - ['setContainer',  ['@service_container']]

    abstract_view:
        abstract: true
        calls:
           - ['setRouter',  ['@router']]
           - ['setSecurity',['@security.token_storage','@security.authorization_checker']]
           - ['setBaseTemplate', ['@app_base_template']]
           - ['setProject', ['%app_project%']]

    abstract_view2:
        abstract: true
        calls:
           - ['setContainer', ['@service_container']]

    abstract_controller:
        abstract: true
        calls: [[setContainer, ['@service_container']]]

    # action index
    index_controller:
        class:  AppBundle\Action\App\Index\IndexController
        parent: abstract_controller

    # action welcome
    welcome_controller:
        class:  AppBundle\Action\App\Welcome\WelcomeController
        parent: abstract_controller

    welcome_view:
        class:  AppBundle\Action\App\Welcome\WelcomeView
        parent: abstract_view2
        arguments:
            - '@user_login_form'
            - '%show_results_menu%'

    # action text alerts
    text_alerts_controller:
        class:  AppBundle\Action\App\TextAlerts\TextAlertsController
        parent: abstract_controller

    text_alerts_view:
        class:  AppBundle\Action\App\TextAlerts\TextAlertsView
        parent: abstract_view2

    # action home
    home_controller:
        class:  AppBundle\Action\App\Home\HomeController
        parent: abstract_controller

    home_view:
        class:  AppBundle\Action\App\Home\HomeView
        parent: abstract_view2
        arguments:
            - '@project_person_repository_v2'
            - '@project_person_view_decorator'
            - '@reg_person_finder'

    # action file
    file_controller:
        class:  AppBundle\Action\App\File\FilePdfController
        parent: abstract_controller

    # action admin
    admin_switch_user_form:
        class:  AppBundle\Action\App\Admin\AdminSwitchUserForm
        parent: abstract_form
        arguments: ['@reg_person_finder']

    admin_controller:
        class:  AppBundle\Action\App\Admin\AdminController
        parent: abstract_controller
        arguments: ['@admin_switch_user_form']

    admin_view:
        class:  AppBundle\Action\App\Admin\AdminView
        parent: abstract_view2
        arguments: ['@admin_switch_user_form']