services:

    app_kernel_listener:
        class:  AppBundle\Listener\KernelListener
        calls: [[setContainer, ['@service_container']]]
        tags:  [{ name: kernel.event_subscriber }]
        arguments: ['%secure_routes%']

    app_base_template:
        class: AppBundle\Action\BaseTemplate
        calls:
            - ['setRouter',  ['@router']]
            - ['setSecurity',['@security.token_storage','@security.authorization_checker']]
            - ['setProject', ['%app_project%']]
        arguments:
            - '%show_header_image%'

    app_page_template: # Depreciated
        abstract: true
        calls:
           - ['setRouter',  ['@router']]
           - ['setSecurity',['@security.token_storage','@security.authorization_checker']]
           - ['setBaseTemplate', ['@app_base_template']]
           - ['setProject', ['%app_project%']]

    abstract_form:
        abstract: true
        calls:
           - ['setContainer',  ['@service_container']]

    abstract_view:
        abstract: true
        calls:
           - ['setRouter',  ['@router']]
           - ['setSecurity',['@security.token_storage','@security.authorization_checker']]
           - ['setBaseTemplate', ['@app_base_template']]
           - ['setProject', ['%app_project%']]

    abstract_view2:
        abstract: true
        calls:
           - ['setContainer', ['@service_container']]

    app_action_abstract_controller: # depreciated
        abstract: true
        calls: [[setContainer, ['@service_container']]]

    abstract_controller:
        abstract: true
        calls: [[setContainer, ['@service_container']]]

    # action index
    index_controller:
        class:  AppBundle\Action\App\Index\IndexController
        parent: abstract_controller

    # action welcome
    welcome_controller:
        class:  AppBundle\Action\App\Welcome\WelcomeController
        parent: abstract_controller

    welcome_view:
        class:  AppBundle\Action\App\Welcome\WelcomeView
        parent: abstract_view
        arguments:
            - '@user_login_form'

    # action home
    home_controller:
        class:  AppBundle\Action\App\Home\HomeController
        parent: abstract_controller

    home_view:
        class:  AppBundle\Action\App\Home\HomeView
        parent: abstract_view
        arguments:
            - '@project_person_repository'
            - '@ayso_volunteer_key_transformer'
            - '@ayso_region_to_sar_transformer'

    # action admin
    admin_controller:
        class:  AppBundle\Action\Admin\AdminController
        parent: abstract_controller
        arguments:
          - '@admin_page_template'
        
    admin_page_template:
        class:  AppBundle\Action\Admin\AdminPageTemplate
        parent: app_page_template


