
game_report_update:
    path: /update/{projectId}/{gameNumber}
    defaults:
        _controller: game_report_update_controller
        _view:       game_report_update_view
        _rolex:       ROLE_SCORE_ENTRY

