services:

    project_person_connection:
        alias: doctrine.dbal.aoc2017_connection

    project_person_repository:
        class: AppBundle\Action\Project\Person\ProjectPersonRepository
        arguments:
            - '@project_person_connection'

    project_person_view_decorator:
        class: AppBundle\Action\Project\Person\ProjectPersonViewDecorator
        arguments:
            - '@phone_transformer'
            - '@cerad.ayso.volunteer_key_transformer'
            - '@cerad.ayso.region_to_sar_transformer'
            - '@project_person_will_referee_transformer'

# ==========================================================================
# Register

    project_person_register_controller:
        class:  AppBundle\Action\Project\Person\Register\RegisterController
        parent: abstract_controller
        arguments:
            - '@project_person_register_form'
            - '@project_person_repository_v2'
            - '@cerad.ayso.finder'
            - '%app_home_route%'
            - '@project_person_register_template_email'

    project_person_register_view:
        class:  AppBundle\Action\Project\Person\Register\RegisterView
        parent: abstract_view2
        arguments:
            - '@project_person_register_form'

    project_person_register_template_email:
        class:  AppBundle\Action\Project\Person\Register\RegisterTemplateEmail
        parent: abstract_view2
        arguments:
            - '@project_person_view_decorator'

    project_person_register_form:
        class:  AppBundle\Action\Project\Person\Register\RegisterForm
        parent: abstract_form
        arguments:
            - '%app_project_controls%'
            - '%app_project_registration_form_controls%'

    project_person_will_referee_transformer:
      class:  AppBundle\Action\Project\Person\ViewTransformer\WillRefereeTransformer