services:

    # Security
    cerad_user_entity_manager:
        alias: doctrine.orm.users_entity_manager

    cerad_user_repository:
        class:  Cerad\Bundle\UserBundle\Entity\UserRepository
        factory: ['@cerad_user_entity_manager','getRepository']
        arguments:  
            - 'Cerad\Bundle\UserBundle\Entity\User'

    cerad_user_provider:
        class:  Cerad\Bundle\UserBundle\Security\UserProvider
        arguments:
            - '@cerad_user_repository'
            - '@event_dispatcher'
            - '@logger'

    cerad_user_encoder:
        class:  Cerad\Bundle\UserBundle\Security\UserEncoder
        arguments:
            - '%cerad_user_master_password%'
            
    cerad_user_event_listener:
        class: Cerad\Bundle\UserBundle\EventListener\UserListener
        calls:
             - [setContainer, ['@service_container']]
     #   tags:
     #       - { name: kernel.event_subscriber }
        arguments:
            - 'cerad_user_repository'

    cerad_user_login_form:
        class: Cerad\Bundle\UserBundle\Action\Login\LoginForm
        arguments:
            - '@security.authentication_utils'
            - '@security.csrf.token_manager'