app:
    resource: "@AppBundle/Resources/config/routes/app.yml"

app_game:
    resource: "@AppBundle/Resources/config/routes/game.yml"
    prefix: /game

app_schedule:
    resource: "@AppBundle/Resources/config/routes/schedule.yml"
    prefix: /schedule

app_results:
    resource: "@AppBundle/Resources/config/routes/results.yml"
    prefix: /results
