services:

    app_action_index_controller:
        class: AppBundle\Action\Index\IndexController
        calls: [[setContainer, ['@service_container']]]
        arguments:
            - '@cerad_user_login_form'
            - '@app_action_index_page_template'

    app_action_index_page_template:
        class: AppBundle\Action\Index\IndexPageTemplate
        parent: app_page_template
        calls: [['setBaseTemplate', ['@app_base_template']]]

    app_base_template:
        class: AppBundle\Action\BaseTemplate

    app_page_template:
        abstract: true
        calls:
           - ['setRouter',  ['@router']]
           - ['setSecurity',['@security.token_storage','@security.authorization_checker']]


