
game_listing:
    path: /listing
    defaults:
        _controller: game_listing_controller
        _view:       game_listing_view_html
        _role:       ROLE_ADMIN

game_export:
    path: /export
    defaults:
        _controller: game_export_controller
        _view:       game_export_view_excel
        _role:       ROLE_ADMIN

game_import:
    path: /import
    defaults:
        _controller: game_listing_controller
        _view:       game_listing_view_html
        _role:       ROLE_ADMIN
