services:

    game_connection:
        alias: doctrine.dbal.ng2019games_connection

#    game_migrate_ng2014_command:
#        class: AppBundle\Action\Game\Migrate\MigrateGames2014Command
#        tags: [{ name: console.command }]
#        arguments:
#            - "@doctrine.dbal.ng2014games_connection"
#            - "@doctrine.dbal.noc2014games_connection"

    game_init_ng2019_command:
        class: AppBundle\Action\Game\Admin\InitSOFNG2019Command
        tags: [{ name: console.command }]
        arguments:
            - "@doctrine.dbal.ng2019games_connection"
            - "%app_project_key%"
            - "%app_project%"

#    game_adjust_ng2016_command:
#        class: AppBundle\Action\Game\Migrate\AdjustGames2016Command
#        tags: [{ name: console.command }]
#        arguments:
#            - "@doctrine.dbal.noc2016games_connection"
#            - "@schedule_finder_2019"
#            - "@game_updater"
#            - "@reg_team_import_reader_excel"

#    game_soccerfest_ng2019_command:
#        class: AppBundle\Action\Game\Migrate\Soccerfest2019Command
#        tags: [{ name: console.command }]
#        arguments:
#            - "@doctrine.dbal.ng2019games_connection"
#            - "@schedule_finder_2019"
#            - "@game_updater"
#            - "@reg_team_import_reader_excel"
#            - "%app_project_key%"

#    game_approve_ng2016_command:
#        class: AppBundle\Action\Game\Migrate\Approve2016Command
#        tags: [{ name: console.command }]
#        arguments:
#            - "@doctrine.dbal.noc2016games_connection"
#            - "@schedule_finder_2019"
#            - "@game_updater"
#            - "@reg_team_import_reader_excel"
#
    game_approve_requested_assignments_ng2019_command:
        class: AppBundle\Action\Game\Admin\ApproveRequestedAssignmentsNG2019Command
        tags: [{ name: console.command }]
        arguments:
            - '%app_project_key%'
            - "@doctrine.dbal.ng2019games_connection"

    game_accept_published_assignments_ng2019_command:
        class: AppBundle\Action\Game\Admin\AcceptPublishedAssignmentsNG2019Command
        tags: [{ name: console.command }]
        arguments:
            - '%app_project_key%'
            - "@doctrine.dbal.ng2019games_connection"

#    game_delete_pool_ng2019_command:
#        class: AppBundle\Action\Game\Admin\DeletePoolNG2019Command
#        tags: [{ name: console.command }]
#        arguments:
#            - '%app_project_key%'
#            - "@doctrine.dbal.ng2019games_connection"

    game_publish_pending_assignments_ng2019_command:
        class: AppBundle\Action\Game\Admin\PublishPendingAssignmentsNG2019Command
        tags: [{ name: console.command }]
        arguments:
            - '%app_project_key%'
            - "@doctrine.dbal.ng2019games_connection"

    game_approve_verified_ng2019_command:
        class: AppBundle\Action\Game\Admin\ApproveVerifiedNG2019Command
        tags: [{ name: console.command }]
        arguments:
            - "@doctrine.dbal.ng2019_connection"
            - "%app_project_key%"

    game_verify_officials_ng2018_command:
        class: AppBundle\Action\Game\Admin\VerifyOfficialsNG2019Command
        tags: [{ name: console.command }]
        arguments:
            - '%app_project_key%'
            - "@doctrine.dbal.ng2019_connection"

    game_removesh_ng2019_command:
        class: AppBundle\Action\Game\Admin\RemoveRefereeSHNG2019Command
        tags: [{ name: console.command }]
        arguments:
            - '%app_project_key%'
            - "@doctrine.dbal.ng2019games_connection"

    game_assignment_conflicts_ng2019_command:
        class: AppBundle\Action\Game\Admin\ReviewAssignmentConflictsNG2019Command
        tags: [{ name: console.command }]
        arguments:
            - '%app_project_key%'
            - "@doctrine.dbal.ng2019games_connection"

#    game_update_19u_pools_ng2019_command:
#        class: AppBundle\Action\Game\Admin\Update19UPoolsNG2019Command
#        tags: [{ name: console.command }]
#        arguments:
#            - '%app_project_key%'
#            - "@doctrine.dbal.ng2019games_connection"

#    game_affinity_tweak_ng2019_command:
#        class: AppBundle\Action\Game\Admin\AffinityTweakNG2019Command
#        tags: [{ name: console.command }]
#        arguments:
#            - '%app_project_key%'
#            - "@doctrine.dbal.ng2019games_connection"

#    game_publish_ng2016_command:
#        class: AppBundle\Action\Game\Migrate\Publish2016Command
#        tags: [{ name: console.command }]
#        arguments:
#            - "@doctrine.dbal.noc2016games_connection"
#            - "@schedule_finder_2019"
#            - "@game_updater"
#            - "@reg_team_import_reader_excel"
#
#    game_publish_noc2016_command:
#        class: AppBundle\Action\Game\Migrate\PublishNOC2016Command
#        tags: [{ name: console.command }]
#        arguments:
#            - '%app_project%'
#            - "@doctrine.dbal.noc2016games_connection"
#            - "@schedule_finder_2019"
#            - "@game_updater"
#            - "@reg_team_import_reader_excel"
#
#    game_open_ng2016_command:
#        class: AppBundle\Action\Game\Migrate\Open2016Command
#        tags: [{ name: console.command }]
#        arguments:
#            - "@doctrine.dbal.noc2016games_connection"
#            - "@schedule_finder_2019"
#            - "@game_updater"
#            - "@reg_team_import_reader_excel"

#    game_seq_numbers_command:
#         class: AppBundle\Action\Game\Migrate\SeqGameNumbersCommand
#         tags: [{ name: console.command }]
#         arguments:
#             - "@doctrine.dbal.ng2019games_connection"
#             - "@game_finder"
#             - "@game_updater"

#    game_validate_command:
#        class: AppBundle\Action\Game\Migrate\ValidateGamesCommand
#        tags: [{ name: console.command }]
#        arguments:
#            - "@doctrine.dbal.ng2019games_connection"
#            - "@game_finder"
#            - "@game_updater"

    game_validate_command:
        class: AppBundle\Action\Game\Admin\VerifyResultsNG2019Command
        tags: [{ name: console.command }]
        arguments:
            - "%app_project_key%"
            - "@doctrine.dbal.ng2019games_connection"

    game_finder:
        class: AppBundle\Action\Game\GameFinder
        arguments:
            - "@doctrine.dbal.ng2019games_connection"
            - "@doctrine.dbal.ng2019games_connection"

    game_updater:
        class: AppBundle\Action\Game\GameUpdater
        arguments:
            - "@doctrine.dbal.ng2019games_connection"

# Admin listing action
    game_listing_search_form:
        class:  AppBundle\Action\Game\Listing\GameListingSearchForm
        parent: abstract_form
        arguments:
            - "%project_choices%"
            - "%projects%"
            - "@game_connection"

    game_listing_controller:
        class:  AppBundle\Action\Game\Listing\GameListingController
        parent: abstract_controller
        arguments:
            - "@game_listing_search_form"
            - "@game_finder"
            - "%project_choices%"
            - "%projects%"

    game_listing_view_html:
        class:  AppBundle\Action\Game\Listing\GameListingView
        parent: abstract_view2
        arguments:
            - "@game_listing_search_form"
            - "@game_finder"

# Admin export action
    game_export_controller:
        class:  AppBundle\Action\Game\Export\GameExportController
        parent: abstract_controller
        arguments:
            - "@game_finder"
            - "%project_choices%"
            - "%projects%"

    game_export_writer_excel:
        class:  AppBundle\Action\Game\Export\GameExportWriterExcel

    game_export_view_excel:
        class:  AppBundle\Action\Game\Export\GameExportViewExcel
        parent: abstract_view2
        arguments:
            - "@game_export_writer_excel"

    # ===========================================
    # Game Import
    game_import_reader_excel:
        class:  AppBundle\Action\Game\Import\GameImportReaderExcel

    game_import_updater:
        class:  AppBundle\Action\Game\Import\GameImportUpdater
        arguments: ["@game_connection"]

    game_import_form:
        class:  AppBundle\Action\Game\Import\GameImportForm
        parent: abstract_controller

    game_import_controller:
        class:  AppBundle\Action\Game\Import\GameImportController
        parent: abstract_controller
        arguments:
            - "@game_import_form"
            - "@game_import_reader_excel"
            - "@game_import_updater"

    game_import_view:
        class:  AppBundle\Action\Game\Import\GameImportView
        parent: abstract_view2
        arguments:
            - "@game_import_form"
