services:

    game_connection:
        alias: doctrine.dbal.ng2016games_connection

    game_migrate_ng2014_command:
        class: AppBundle\Action\Game\Migrate\MigrateGames2014Command
        tags: [{ name: console.command }]
        arguments:
            - '@doctrine.dbal.ng2014games_connection'
            - '@doctrine.dbal.ng2016games_connection'

    game_init_ng2016_command:
        class: AppBundle\Action\Game\Migrate\InitGames2016Command
        tags: [{ name: console.command }]
        arguments:
            - '@doctrine.dbal.ng2016games_connection'
