services:

    game_connection:
        alias: doctrine.dbal.ng2016games_connection

    game_migrate_ng2014_command:
        class: AppBundle\Action\Game\Migrate\MigrateGames2014Command
        tags: [{ name: console.command }]
        arguments:
            - '@doctrine.dbal.ng2014games_connection'
            - '@doctrine.dbal.ng2016games_connection'

    game_init_ng2016_command:
        class: AppBundle\Action\Game\Migrate\InitGames2016Command
        tags: [{ name: console.command }]
        arguments:
            - '@doctrine.dbal.ng2016games_connection'

# Admin listing action
    game_listing_search_form:
        class:  AppBundle\Action\Game\Listing\GameListingSearchForm
        parent: abstract_form
        arguments:
            - '%project_choices%'
            - '%projects%'
            - '@game_connection'

    game_listing_controller:
        class:  AppBundle\Action\Game\Listing\GameListingController
        parent: abstract_controller
        arguments:
            - '@game_listing_search_form'
            - '%project_choices%'
            - '%projects%'

    game_listing_view_html:
        class:  AppBundle\Action\Game\Listing\GameListingView
        parent: abstract_view2
        arguments:
            - '@game_listing_search_form'
