services:
    _defaults: { public: true }

    game_connection:
        public: true
        alias: doctrine.dbal.ng2019games_connection

    game_seq_numbers_command:
        public: true
        class: AppBundle\Action\Game\Migrate\SeqGameNumbersCommand
        tags: [{ name: console.command }]
        arguments:
            - '@doctrine.dbal.ng2019games_connection'
            - '@game_finder'
            - '@game_updater'

    game_validate_command:
        public: true
        class: AppBundle\Action\Game\Migrate\ValidateGamesCommand
        tags: [{ name: console.command }]
        arguments:
            - '@doctrine.dbal.ng2019games_connection'
            - '@game_finder'
            - '@game_updater'

    game_finder:
        public: true
        class: AppBundle\Action\Game\GameFinder
        arguments:
            - '@doctrine.dbal.ng2019games_connection'
            - '@doctrine.dbal.ng2019games_connection'

    game_updater:
        public: true
        class: AppBundle\Action\Game\GameUpdater
        arguments:
            - '@doctrine.dbal.ng2019games_connection'

# Admin listing action
    game_listing_search_form:
        public: true
        class:  AppBundle\Action\Game\Listing\GameListingSearchForm
        parent: abstract_form
        arguments:
            - '%project_choices%'
            - '%projects%'
            - '@game_connection'

    game_listing_controller:
        public: true
        class:  AppBundle\Action\Game\Listing\GameListingController
        parent: abstract_controller
        arguments:
            - '@game_listing_search_form'
            - '@game_finder'
            - '%project_choices%'
            - '%projects%'

    game_listing_view_html:
        public: true
        class:  AppBundle\Action\Game\Listing\GameListingView
        parent: abstract_view2
        arguments:
            - '@game_listing_search_form'
            - '@game_finder'

# Admin export action
    game_export_controller:
        public: true
        class:  AppBundle\Action\Game\Export\GameExportController
        parent: abstract_controller
        arguments:
            - '@game_finder'
            - '%project_choices%'
            - '%projects%'

    game_export_writer_excel:
        public: true
        class:  AppBundle\Action\Game\Export\GameExportWriterExcel

    game_export_view_excel:
        public: true
        class:  AppBundle\Action\Game\Export\GameExportViewExcel
        parent: abstract_view2
        arguments:
            - '@game_export_writer_excel'

    # ===========================================
    # Game Import
    game_import_reader_excel:
        public: true
        class:  AppBundle\Action\Game\Import\GameImportReaderExcel

    game_import_updater:
        public: true
        class:  AppBundle\Action\Game\Import\GameImportUpdater
        arguments: ['@game_connection']

    game_import_form:
        public: true
        class:  AppBundle\Action\Game\Import\GameImportForm
        parent: abstract_controller

    game_import_controller:
        public: true
        class:  AppBundle\Action\Game\Import\GameImportController
        parent: abstract_controller
        arguments:
            - '@game_import_form'
            - '@game_import_reader_excel'
            - '@game_import_updater'

    game_import_view:
        public: true
        class:  AppBundle\Action\Game\Import\GameImportView
        parent: abstract_view2
        arguments:
            - '@game_import_form'
