services:

    _defaults: { public: true }

    reg_team_connection:
<<<<<<< HEAD
        public: true
        alias: doctrine.dbal.ng2019games_connection

    reg_person_connection:
        public: true
=======
        alias: doctrine.dbal.ng2019games_connection

    reg_person_connection:
>>>>>>> ng2019x2
        alias: doctrine.dbal.ng2019_connection

    reg_person_finder:
        public: true
        class: AppBundle\Action\RegPerson\RegPersonFinder
        arguments:
            - '@reg_person_connection'
            - '@reg_team_connection'
            - '@user_connection'

    reg_person_updater:
        public: true
        class: AppBundle\Action\RegPerson\RegPersonUpdater
        arguments:
            - '@reg_person_connection'
            - '@reg_team_connection'

    reg_person_norefrole_ng2019_command:
        class: AppBundle\Action\RegPerson\Admin\MissingRefRoleNG2019Command
        tags: [{ name: console.command }]
        arguments:
            - '%app_project_key%'
            - '@reg_person_connection'

    # ===========================================
    # RegPersonPerson Update
    reg_person_persons_update_form:
        public: true
        class:  AppBundle\Action\RegPerson\Persons\Update\PersonsUpdateForm
        parent: abstract_form
        arguments:
            - '@reg_person_finder'

    reg_person_persons_update_controller:
        public: true
        class:  AppBundle\Action\RegPerson\Persons\Update\PersonsUpdateController
        parent: abstract_controller
        arguments:
            - '@reg_person_persons_update_form'
            - '@reg_person_finder'
            - '@reg_person_updater'

    reg_person_persons_update_view:
        public: true
        class:  AppBundle\Action\RegPerson\Persons\Update\PersonsUpdateView
        parent: abstract_view2
        arguments:
            - '@reg_person_persons_update_form'

    # ===========================================
    # RegPersonTeam Update
    reg_person_teams_update_form:
        public: true
        class:  AppBundle\Action\RegPerson\Teams\Update\TeamsUpdateForm
        parent: abstract_form
        arguments:
            - '@reg_person_finder'

    reg_person_teams_update_controller:
        public: true
        class:  AppBundle\Action\RegPerson\Teams\Update\TeamsUpdateController
        parent: abstract_controller
        arguments:
            - '@reg_person_teams_update_form'
            - '@reg_person_finder'
            - '@reg_person_updater'

    reg_person_teams_update_view:
        public: true
        class:  AppBundle\Action\RegPerson\Teams\Update\TeamsUpdateView
        parent: abstract_view2
        arguments:
            - '@reg_person_teams_update_form'
