services:

    reg_team_connection:
        alias: doctrine.dbal.aoc2017games_connection

    reg_person_connection:
        alias: doctrine.dbal.aoc2017_connection

    reg_person_finder:
        class: AppBundle\Action\RegPerson\RegPersonFinder
        arguments:
            - '@reg_person_connection'
            - '@reg_team_connection'
            - '@user_connection'

    reg_person_updater:
        class: AppBundle\Action\RegPerson\RegPersonUpdater
        arguments:
            - '@reg_person_connection'
            - '@reg_team_connection'

    # ===========================================
    # RegPersonPerson Update
    reg_person_persons_update_form:
        class:  AppBundle\Action\RegPerson\Persons\Update\PersonsUpdateForm
        parent: abstract_form
        arguments:
            - '@reg_person_finder'

    reg_person_persons_update_controller:
        class:  AppBundle\Action\RegPerson\Persons\Update\PersonsUpdateController
        parent: abstract_controller
        arguments:
            - '@reg_person_persons_update_form'
            - '@reg_person_finder'
            - '@reg_person_updater'

    reg_person_persons_update_view:
        class:  AppBundle\Action\RegPerson\Persons\Update\PersonsUpdateView
        parent: abstract_view2
        arguments:
            - '@reg_person_persons_update_form'

    # ===========================================
    # RegPersonTeam Update
    reg_person_teams_update_form:
        class:  AppBundle\Action\RegPerson\Teams\Update\TeamsUpdateForm
        parent: abstract_form
        arguments:
            - '@reg_person_finder'

    reg_person_teams_update_controller:
        class:  AppBundle\Action\RegPerson\Teams\Update\TeamsUpdateController
        parent: abstract_controller
        arguments:
            - '@reg_person_teams_update_form'
            - '@reg_person_finder'
            - '@reg_person_updater'

    reg_person_teams_update_view:
        class:  AppBundle\Action\RegPerson\Teams\Update\TeamsUpdateView
        parent: abstract_view2
        arguments:
            - '@reg_person_teams_update_form'
