schedule_team_2019:
    path: /team.{_format}
    defaults:
        _format: html
        _controller: schedule_team_controller_2019
        _view_html:  schedule_team_view_html_2019
        _view_xls:   schedule_team_view_xls_2019
        _view_csv:   schedule_team_view_csv_2019
        _view_txt:   schedule_team_view_txt_2019

schedule_official_2019:
    path: /official.{_format}
    defaults:
        _format: html
        _controller: schedule_official_controller_2019
        _view_html:  schedule_official_view_html_2019
        _view_xls:   schedule_official_view_xls_2019
        _view_csv:   schedule_official_view_csv_2019
        _view_txt:   schedule_official_view_txt_2019

schedule_assignor_2019:
    path: /assignor.{_format}
    defaults:
        _format: html
        _controller: schedule_assignor_controller_2019
        _view_html:  schedule_assignor_view_html_2019
        _view_xls:   schedule_assignor_view_excel_2019
        #_view_csv:   schedule_assignor_view_csv_2019
        #_view_txt:   schedule_assignor_view_txt_2019

schedule_game_2019:
    path: /game.{_format}
    defaults:
        _format: html
        _controller: schedule_game_controller_2019
        _view_html:  schedule_game_view_html_2019
        _view_xls:   schedule_game_view_xls_2019
        _view_csv:   schedule_game_view_csv_2019
        _view_txt:   schedule_game_view_txt_2019
        _view_pdf:   schedule_game_view_pdf
        _view_json:  schedule_game_view_json

schedule_my_2019:
    path: /my.{_format}
    defaults:
        _format: html
        _controller: schedule_my_controller_2019
        _view_html:  schedule_my_view_html_2019
        _view_txt:   schedule_game_view_txt_2019

schedule_medalroundcalc_2019:
    path: /medalroundcalc.{_format}
    defaults:
        _format: xls_qf
        _controller:    schedule_medalroundcalc_controller_2019
        _view_xls_qf:   schedule_medalroundcalc_view_xls_qf_2019
        _view_xls_sf:   schedule_medalroundcalc_view_xls_sf_2019
        _view_xls_tf:   schedule_medalroundcalc_view_xls_tf_2019

field_map:
    path: /field_map
    defaults:
        fileType: pdf # For future use, only pdf is currently supported
        fileName: 2019NG_FieldMap_Final.pdf
        _controller: file_controller
