services:

    schedule_connection:
        alias: doctrine.dbal.ng2014games_connection

    app_action_schedule_repository:
        class: AppBundle\Action\Schedule\ScheduleRepository
        arguments: ['@schedule_connection']

    schedule_team_controller:
        class: AppBundle\Action\Schedule\Team\ScheduleTeamController
        parent: abstract_controller
        arguments:
            - '@app_action_schedule_repository'

    schedule_team_view_html:
        class: AppBundle\Action\Schedule\Team\ScheduleTeamView
        parent: abstract_view
        arguments:
            - '@app_action_schedule_repository'

    schedule_team_view_csv:
        class: AppBundle\Action\Schedule\Team\ScheduleTeamViewFile
        parent: abstract_view
        arguments:
            - '@app_action_schedule_repository'
            - '@abstract_exporter_csv'

    schedule_team_view_xls:
        class: AppBundle\Action\Schedule\Team\ScheduleTeamViewFile
        parent: abstract_view
        arguments:
            - '@app_action_schedule_repository'
            - '@abstract_exporter_xls'

    abstract_exporter_xls:
        class: AppBundle\Action\AbstractExporter
        arguments:
            - 'xls'

    abstract_exporter_csv:
        class: AppBundle\Action\AbstractExporter
        arguments:
            - 'csv'

    abstract_exporter_txt:
        class: AppBundle\Action\AbstractExporter
        arguments:
            - 'txt'

    schedule_game_controller:
        class: AppBundle\Action\Schedule\Game\ScheduleGameController
        parent: abstract_controller
        arguments:
            - '@app_action_schedule_repository'

    schedule_game_view_html:
        class: AppBundle\Action\Schedule\Game\ScheduleGameView
        parent: abstract_view
        arguments:
            - '@app_action_schedule_repository'

    schedule_game_view_csv:
        class: AppBundle\Action\Schedule\Game\ScheduleGameViewFile
        parent: abstract_view
        arguments:
            - '@app_action_schedule_repository'
            - '@abstract_exporter_csv'            

    schedule_game_view_xls:
        class: AppBundle\Action\Schedule\Game\ScheduleGameViewFile
        parent: abstract_view
        arguments:
            - '@app_action_schedule_repository'
            - '@abstract_exporter_xls'

    schedule_game_core_xls:
        class: AppBundle\Action\Schedule\Game\ScheduleGameViewCore
        parent: abstract_view
        arguments:
            - '@app_action_schedule_repository'
            - '@abstract_exporter_xls'
