services:

    abstract_exporter_xls:
        class: AppBundle\Action\AbstractExporter
        arguments:
            - "xls"

    abstract_exporter_csv:
        class: AppBundle\Action\AbstractExporter
        arguments:
            - "csv"

    abstract_exporter_txt:
        class: AppBundle\Action\AbstractExporter
        arguments:
            - "txt"

    schedule_finder_2019:
        class: AppBundle\Action\Schedule\ScheduleFinder
        arguments:
            - "@doctrine.dbal.ng2019games_connection" # gameConn
            - "@doctrine.dbal.ng2019games_connection" # regTeamConn
            - "@reg_person_finder"

    schedule_template_2019:
        abstract: true
        calls:
            - ["setContainer",       ["@service_container"]]
            - ["setRegPersonFinder", ["@reg_person_finder"]]

    schedule_search_form_2019:
        class:  AppBundle\Action\Schedule\ScheduleSearchForm
        parent: abstract_form
        arguments:
            - "%project_choices%"
            - "%projects%"

    # ===============================================================
    # Schedule Game
    schedule_game_search_form_2019:
        class:  AppBundle\Action\Schedule\Game\ScheduleGameSearchForm
        parent: abstract_form
        arguments:
            - "%project_choices%"
            - "%projects%"

    schedule_game_controller_2019:
        class:  AppBundle\Action\Schedule\Game\ScheduleGameController
        parent: abstract_controller
        arguments:
            - "@schedule_search_form_2019"
            - "@schedule_finder_2019"
            - "%project_choices%"
            - "%projects%"

    schedule_game_template_2019:
        class:  AppBundle\Action\Schedule\ScheduleTemplate
        parent: schedule_template_2019
        arguments: ["Game Schedule"]

    schedule_game_view_html_2019:
        class:  AppBundle\Action\Schedule\ScheduleView
        parent: abstract_view2
        arguments:
            - "@schedule_search_form_2019"
            - "@schedule_game_template_2019"

    schedule_game_writer_excel:
        class:  AppBundle\Action\Schedule\Game\ScheduleGameWriterExcel

    schedule_game_view_xls_2019:
        class:  AppBundle\Action\Schedule\Game\ScheduleGameViewFile
        parent: abstract_view2
        arguments:
            - "@abstract_exporter_xls"
            
    schedule_game_view_csv_2019:
        class:  AppBundle\Action\Schedule\Game\ScheduleGameViewFile
        parent: abstract_view2
        arguments:
            - "@abstract_exporter_csv"
            
    schedule_game_view_txt_2019:
        class:  AppBundle\Action\Schedule\Game\ScheduleGameViewFile
        parent: abstract_view2
        arguments:
            - "@abstract_exporter_txt"

    # ===============================================================
    # Schedule Official
    schedule_official_controller_2019:
        class:  AppBundle\Action\Schedule\Official\ScheduleOfficialController
        parent: abstract_controller
        arguments:
            - "@schedule_search_form_2019"
            - "@schedule_finder_2019"
            - "%project_choices%"
            - "%projects%"

    schedule_official_template_2019:
        class:  AppBundle\Action\Schedule\ScheduleTemplate
        parent: schedule_template_2019
        arguments:
            - "Referee Game Schedule"
            - true
            - false
            - "@game_official_assign_workflow"

    schedule_official_view_html_2019:
        class:  AppBundle\Action\Schedule\ScheduleView
        parent: abstract_view2
        arguments:
            - "@schedule_search_form_2019"
            - "@schedule_official_template_2019"

    schedule_official_view_xls_2019:
        class:  AppBundle\Action\Schedule\Official\ScheduleOfficialViewFile
        parent: abstract_view2
        arguments:
            - "@abstract_exporter_xls"

    schedule_official_view_txt_2019:
        class:  AppBundle\Action\Schedule\Official\ScheduleOfficialViewFile
        parent: abstract_view2
        arguments:
            - "@abstract_exporter_txt"

    # ===============================================================
    # Schedule Assignor
    schedule_assignor_search_form_2019:
        class:  AppBundle\Action\Schedule\Assignor\ScheduleAssignorSearchForm
        parent: abstract_form
        arguments:
            - "%project_choices%"
            - "%projects%"

    schedule_assignor_controller_2019:
        class:  AppBundle\Action\Schedule\Assignor\ScheduleAssignorController
        parent: abstract_controller
        arguments:
            - "@schedule_assignor_search_form_2019"
            - "@schedule_finder_2019"
            - "%project_choices%"
            - "%projects%"

    schedule_assignor_template_2019:
        class:  AppBundle\Action\Schedule\ScheduleTemplate
        parent: schedule_template_2019
        arguments:
            - "Assignor Game Schedule"
            -  true
            -  true
            - "@game_official_assign_workflow"
            - "@game_official_details_finder"

    schedule_assignor_view_html_2019:
        class:  AppBundle\Action\Schedule\ScheduleView
        parent: abstract_view2
        arguments:
            - "@schedule_assignor_search_form_2019"
            - "@schedule_assignor_template_2019"

    schedule_assignor_view_excel_2019:
        class:  AppBundle\Action\Schedule\Assignor\ScheduleAssignorViewExcel
        parent: abstract_view2
        arguments:
            - "@schedule_assignor_writer_excel_2019"

    schedule_assignor_writer_excel_2019:
        class:  AppBundle\Action\Schedule\Assignor\ScheduleAssignorWriterExcel
        arguments:
            - "@game_official_assign_workflow"
            - "@game_official_details_finder"
            - "@phone_transformer"
            - "@shirt_size_transformer"

    # ===============================================================
    # Schedule My
    schedule_my_search_form_2019:
        class:  AppBundle\Action\Schedule\My\ScheduleMySearchForm
        parent: abstract_form

    schedule_my_controller_2019:
        class:  AppBundle\Action\Schedule\My\ScheduleMyController
        parent: abstract_controller
        arguments:
            - "@schedule_my_search_form_2019"
            - "@schedule_finder_2019"

    schedule_my_template_2019:
        class:  AppBundle\Action\Schedule\ScheduleTemplate
        parent: schedule_template_2019
        arguments: ["My Game Schedule", true, false, "@game_official_assign_workflow"]

    schedule_my_view_html_2019:
        class:  AppBundle\Action\Schedule\My\ScheduleMyView
        parent: abstract_view2
        arguments:
            - "@schedule_my_search_form_2019"
            - "@schedule_my_template_2019"

    schedule_my_view_txt_2019:
        class:  AppBundle\Action\Schedule\My\ScheduleMyViewFile
        parent: abstract_view2
        arguments:
            - "@abstract_exporter_txt"

    # ===============================================================
    # Schedule Team
    schedule_team_search_form_2019:
        class:  AppBundle\Action\Schedule\Team\ScheduleTeamSearchForm
        parent: abstract_form
        arguments:
            - "%project_choices%"
            - "%projects%"
            - "@schedule_finder_2019"

    schedule_team_controller_2019:
        class:  AppBundle\Action\Schedule\Team\ScheduleTeamController
        parent: abstract_controller
        arguments:
            - "@schedule_team_search_form_2019"
            - "@schedule_finder_2019"
            - "%project_choices%"
            - "%projects%"

    schedule_team_template_2019:
        class:  AppBundle\Action\Schedule\ScheduleTemplate
        parent: schedule_template_2019
        arguments: ["Team Schedule"]

    schedule_team_view_html_2019:
        class:  AppBundle\Action\Schedule\Team\ScheduleTeamView
        parent: abstract_view2
        arguments:
            - "@schedule_team_search_form_2019"
            - "@schedule_team_template_2019"

    schedule_team_view_xls_2019:
        class:  AppBundle\Action\Schedule\Team\ScheduleTeamViewFile
        parent: abstract_view2
        arguments:
            - "@abstract_exporter_xls"
            
    schedule_team_view_csv_2019:
        class:  AppBundle\Action\Schedule\Team\ScheduleTeamViewFile
        parent: abstract_view2
        arguments:
            - "@abstract_exporter_csv"

    schedule_team_view_txt_2019:
        class:  AppBundle\Action\Schedule\Team\ScheduleTeamViewFile
        parent: abstract_view2
        arguments:
            - "@abstract_exporter_txt"
            
    # ===============================================================
    # Schedule MedalRoundLogic
    schedule_medalroundcalc_controller_2019:
        class: AppBundle\Action\Schedule\MedalRound\ScheduleMedalRoundController
        parent: abstract_controller
        arguments:
            - "@results_finder_2019"
            - "%project_choices%"

    schedule_medalround_calculator_2019:
        class: AppBundle\Action\Schedule\MedalRound\ScheduleMedalRoundCalculator
        
    schedule_medalroundcalc_view_xls_qf_2019:
        class: AppBundle\Action\Schedule\MedalRound\ScheduleMedalRoundViewFile
        parent: abstract_view2
        arguments:
            - "qf"
            - "@schedule_medalround_calculator_2019"
            - "@results_finder_2019"
            - "@abstract_exporter_xls"

    schedule_medalroundcalc_view_xls_sf_2019:
        class: AppBundle\Action\Schedule\MedalRound\ScheduleMedalRoundViewFile
        parent: abstract_view2
        arguments:
            - "sf"
            - "@schedule_medalround_calculator_2019"
            - "@results_finder_2019"
            - "@abstract_exporter_xls"

    schedule_medalroundcalc_view_xls_tf_2019:
        class: AppBundle\Action\Schedule\MedalRound\ScheduleMedalRoundViewFile
        parent: abstract_view2
        arguments:
            - "fm"
            - "@schedule_medalround_calculator_2019"
            - "@results_finder_2019"
            - "@abstract_exporter_xls"

    # ===============================================================
    # Schedule Commands

    ayso_games_selfassign_command:
        class: AppBundle\Action\Schedule\UpdateSelfAssignCommand
        tags: [{ name: console.command }]
        arguments:
            - "@ng.games.connection"
            - "%app_project_key%"
            - "%app_project%"


