# Fed
services:

    _defaults: { autowire: true, autoconfigure: true, public: false }

    Zayso\Common\:
        resource: './*'

    Zayso\Common\Template\PageTemplate:
        arguments:
            - '%show_header_image%'
            - '%show_schedules_menu%'
            - '%show_results_menu%'
            - '%show_final_results%'
            - '%app_version%'