services:

    ayso_connection:
        alias: doctrine.dbal.ayso_connection

    ayso_repository:
        class: AppBundle\Action\Physical\Ayso\PhysicalAysoRepository
        arguments: ['@ayso_connection']

    ayso_load_command:
        class: AppBundle\Action\Physical\Ayso\Load\AysoLoadCommand
        tags: [{ name: console.command }]
        arguments:
            - '@ayso_connection'

    ayso_region_key_transformer:
        class:  AppBundle\Action\Physical\Ayso\DataTransformer\RegionKeyTransformer

    ayso_volunteer_key_transformer:
        class:  AppBundle\Action\Physical\Ayso\DataTransformer\VolunteerKeyTransformer

    ayso_region_to_sar_transformer:
        class:  AppBundle\Action\Physical\Ayso\DataTransformer\RegionToSarTransformer
        arguments: ['@ayso_repository']